### ISSUE TITLE
[service] Recipe changes affect previous builds

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan-center-index#11953] opened 2022-07-28 14:30 UTC
When a recipe is updated on conan center, it affects all versions and can break builds without any code change!
This is a pretty bad, as one day your build works, and if you build the same commit a day later it might not work as the recipe was changed on CCI which then causes your build to fail.

**Comment by Sil3ntStorm** [comment] 2022-07-28 23:27
I tried that after the recent changes to the googleapis recipe caused (seemingly) many issues. However that resulted in errors like not finding a recipe for protobuf/3.21.1#0 when requesting protobuf without an RREV.

I don't really fancy having to provide an RREV for all (or even most) requires, I'd rather just have it as a quick emergency fix / worst case scenario (e.g. CCI broke stuff that needs a CCI fix) band-aid kind of deal.

**Comment by uilianries** [comment] 2022-07-29 09:13
Just like Croydon mentioned, if need to keep stability on your side, and can't move forward with recipes update, or new Conan releases. Use [lockfiles](https://docs.conan.io/en/latest/versioning/lockfiles/introduction.html) feature. You can generate a lockfile, which will point RREV, you don't need mimic one-by-one. Also, for Conan 2.0 (It's on Beta release now), lockfiles have been redesigned, for better: https://github.com/conan-io/tribe/blob/a36de8dd33852f43091e9f5eb5a7ad83618089f2/design/034-new_lockfiles.md

**Comment by Sil3ntStorm** [comment] 2022-08-01 11:40
It's not really about "stability" or "not updating" more than changes causing build failures.

Using revisions also appears to be causing a ton of issues on its own in that conan claims that the remote does not have binary packages for a recipe which were uploaded and are in fact present on the remote, with the exact hash it requires.
I don't quite understand how or why it won't find stuff that is clearly present in the remote.

That single recipe change has caused several days of outages, pain and suffering so far, with the proposed solutions only causing further headaches, pain and suffering.

**Comment by Sil3ntStorm** [comment] 2022-08-01 14:18
The proposed solution is to use features marked as experimental, which when used causes consumers to not find binary packages for some reason, despite listing the exact same hash that was built and uploaded using the very same system just a few minutes prior. It also produces confusing warnings about dependency "a/1.2.3" being overridden with "a/1.2.3" (no visible difference).

How is one supposed to be using lockfiles for multiple build configurations (i.e. Windows, Linux, Android, Mac, iOS)? These lock files presumably would have to be part of the code base and it would have to be possible to generate a single lock file for all aforementioned configurations from a single developer system.

**Comment by jgsogo** [comment] 2022-08-01 14:39
Hi! Croydon pointed to the best answer so far, this is an issue we need to live with within any central repository. We cannot afford to build all the consumers when a recipe is modified, it's too much time and resources.

Before continuing just a quick note, **you wrote `protobuf/3.21.1#0`, which means that you don't have revisions enabled** in your client/organization (remember you can share settings across an organization)... Please, double check it because it can be the root of many frustrations.

Lockfiles work _good enough_ and have successfully used them in my projects.... but only `--base` lockfiles, full lockfiles are not supposed to be used for development as they can capture just one configuration (with package-id and revision). But _base lockfiles_ capture just the recipe-revision and can be shared between different configurations (Windows, Linux,...) so they are suitable to prevent some of the issues that you mention. Not all, it is not a silver bullet, and there are bugs that are not going to be fixed in v1.

Conan v2 should do lockfiles the right way, but it is still beta. 


---

About some of your issues, maybe you can share reproducible scenarios if you want us to provide some answers, explanations or workarounds. On a generic and abstract level, it is very hard to provide actual feedback or answers. Not sure if those questions belong to CCI repository or Conan one, but we can always move the issues to other repositories if they become too offtopic.

**Comment by Sil3ntStorm** [comment] 2022-08-02 10:01
It seems as though there is an issue due to Windows producing a different revision of the recipe than other systems. Presumably due to the fact that windows is deleting the fPIC option from the recipe.

The Windows recipe being the "newer" one seems to make it not work on other systems, which are complaining about missing binary packages, that the same system built before and that is available in the remote with the exact same hash that it is looking for and complaining about not finding.

I am even requiring a different revision on Windows than on other systems, but it appears it's getting the latest version rather than the one explicitly stated in the requires. At least that is my best guess right now...

**Comment by jgsogo** [comment] 2022-08-02 10:56
The recipe revision is based on the hash of the files, nothing related to logic. If Windows is creating different recipe-revisions, maybe it is modifying line endings while checking out the files from Git. This is something that you should configure in your Git client.

About `googleapis`. Now the recipe builds the actual libraries instead of packaging just the `proto` files. This approach is safer than generating from the protos in each of the projects that consume them (like `grpc-proto`, `grpc` and `google-cloud-cpp`). If each project generates its own protos and they are used in the same graph, it can happen that different versions of those protos are being used together and, if using shared libraries, there will be ODR violations that protobuf itself will raise as errors on startup.

Of course, it can happen that building the libraries fails in Android, CCI doesn't build neither test Android configuration. I really encourage you to work (or share more information) on one of this directions:
1. try to fix the build for Android
2. add an option to `googleapis` that you can use to skip the build and package just the `.proto` files.

**Comment by Sil3ntStorm** [comment] 2022-08-02 11:57
I resigned and am currently eliminating the use of CCI entirely, which will likely bite me in the future when I actually want some updates as that will then be a manual action, but alas. Right now it seems much better than having to waste another week (now and in the future whenever CCI decides to break the next thing). Unfortunately revisions just seem to cause way more pain, headache, confusing errors and inexplicable failures than they seem to be worth. At least that's what it seems like to me right now. Having fought with inexplicable failures for about a week now, I am way past to point of caring at this point in time.

**Comment by jgsogo** [comment] 2022-08-03 13:58
AFAIK, revisions will be enabled by default in Conan v2, so if you have any feedback about them maybe it is good timing to share it now that beta versions are being released (better in Conan repository than here). 

Regarding CCI, these breaking changes will keep happening from time to time, we try to avoid them as much as possible and contributors are doing a huge work in this sense, but there will always be something that breaks for any change (even if it is considered a bug in the recipe, someone will be relying on it). The best advice we can give is what is written in the documentation that was linked in the first answer.

We can improve that documentation or try to explain it in more detail, but lockfiles+revisions and in-house repository are the features we can offer in Conan v1 to alleviate these issues. Conan v2 will release more and better features, we really hope it will be more straightforward to use regarding these use cases.

Thanks for your time and your feedback, and sorry if the answers/features were not good enough. Hope to keep seeing you around in any case 😊

**Closed by jgsogo** 2022-08-03 13:58 UTC
Labels: question
