### ISSUE TITLE
[question] Using local sources in the conandata.yml "url" field 

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan-center-index#10623] opened 2022-05-04 16:38 UTC
I'm helping to setup my organization with Conan and I decided that for the custom packages that would have to be added to our remote I'd copy the style of the Conan center, one thing I'm wondering though. In the `url` field of the `conandata.yml` file can that point to a local archive using `file://` or does the current setup not support this? Is there a another recommended practice for having source archives local while still supporting multiple versions of a package?

**Comment by SpaceIm** [comment] 2022-05-04 17:17
Seems to be a duplicate of https://github.com/conan-io/conan/issues/8846

**Closed as completed** 2022-05-04 17:33 UTC
Labels: question
