### ISSUE TITLE
[package] qt/6.2.4: extra -D in EXTRA_DEFINES

### ISSUE THREAD

**Issue by technic** [conan-io/conan-center-index#14661] opened 2022-12-09 14:53 UTC
### Description

After building qt package I get:

cat res/archdatadir/mkspecs/qmodule.pri

`EXTRA_DEFINES += -DU_STATIC_IMPLEMENTATION -DPCRE2_STATIC`

This is wrong because of extra "-D" flag.

Maybe related:
https://github.com/conan-io/conan-center-index/pull/6301
https://github.com/conan-io/conan-center-index/issues/5290

### Package and Environment Details

* Package Name/Version: **qt/6.2.4**
* Operating System+version: **Linux Ubuntu 22.04**
* Compiler+version: **GCC 10**
* Conan version: **conan 1.53**
* Python version: **Python 3**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=10
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install -r conancenter qt/6.2.4@ -pr:b=default -pr:h=default -b missing

### Logs

Qt  built without errors.

**Comment by technic** [comment] 2022-12-09 16:12
Also this whole approach here https://github.com/conan-io/conan-center-index/blame/master/recipes/qt/6.x.x/conanfile.py#L459 looks wrong for me.

Because then we have absolute paths to other packages inside qt package, which requires that qt has full_version + revision dependency type on these packages!

**Comment by ericLemanissier** [comment] 2022-12-09 16:39
can you please try with https://github.com/conan-io/conan-center-index/pull/14592 ?

**Comment by technic** [comment] 2022-12-09 21:04
So far I removed those lines and changed to qt_find_package_multi generator

**Comment by ericLemanissier** [comment] 2022-12-13 15:52
this should be closed now that https://github.com/conan-io/conan-center-index/commit/6905611c7e1c84dc7b0ed0b2b7b7f0e19c883d21 is merged

**Comment by ericLemanissier** [comment] 2023-01-13 09:19
@technic can you please retry with the current recipe on conan-center (use `-u` command line argument). If the problem is fixed you can close this issue.

**Comment by ericLemanissier** [comment] 2023-01-13 14:11
the current is `qt/6.4.1@#a4a6e592bb7c2310c36492de555fbcff`
`2f0dd245ab48211a5cd65a002b551422` `f9d7d8b263f9421225a599686bb451c7` or `06fa367f56ec5195ea70b83d70312619` should be fine too, but you'd better use the latest one

**Closed** 2023-01-13 15:18 UTC
Labels: bug
