### ISSUE TITLE
[package] msys2/20190524 circular dependency

### ISSUE THREAD

**Issue by spoofedex** [conan-io/conan-center-index#1886] opened 2020-06-12 09:08 UTC
Hi all,

There's a circular dependency in msys2/20190524:
 - msys2 has a build dependency on 7zip
 - 7zip has a build dependency on lzma_sdk
 - lzma_sdk has a build dependency on msys2

This makes building the packages from source impossible.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **msys2/20190524**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2015**
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.7.3**

### Steps to reproduce
Execute:
```
conan install msys2/20190524@_/_ --build *
```

### Logs
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

msys2/20190524: Forced build from source
7zip/19.00: Forced build from source
lzma_sdk/9.20: Forced build from source
make/4.2.1: Forced build from source
ERROR: Loop detected in context host: 'lzma_sdk/9.20' requires 'msys2/20190524' which is an ancestor too
```

Best regards,
SpoofedEx

**Comment by SpaceIm** [comment] 2020-06-12 09:13
Same issue than https://github.com/conan-io/conan-center-index/issues/780

Seems like there was several attempts to fix this, unsuccessful for the moment: https://github.com/conan-io/conan-center-index/pull/1060 https://github.com/conan-io/conan-center-index/pull/1810

**Comment by Croydon** [comment] 2020-06-12 11:06
Yes, please close as a duplicate of #780

**Closed** 2020-06-12 11:17 UTC
Labels: bug
