### ISSUE TITLE
[package] ms-gsl/2.1.0: `CONAN_PKG::ms-gsl` target not found

### ISSUE THREAD

**Issue by bysnack** [conan-io/conan-center-index#7925] opened 2021-11-02 12:18 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ms-gsl/2.1.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **Clang 10**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.40.3**
  * Python version: **Python 3.8.10**

### Details

Linking using the `CONAN_PKG::ms-gsl` target doesn't seem to work anymore after https://github.com/conan-io/conan-center-index/pull/7890 got merged

```cmake
...
target_link_libraries(test PUBLIC CONAN_PKG::ms-gsl)
...
```

Will produce
```
CMake Error at bootstrap_more/packaging.cmake:20 (add_library):
  Target "test" links to target "CONAN_PKG::ms-gsl" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
Using the recipe prior to that change this works just fine.

Note that doing so with the `CONAN_PKG::Microsoft.GSL` does seem to work.

I am lacking the time to make a more detailed bug report at the moment, so I hope this clear enough, otherwise I'll update it later.

**Comment by darcamo** [comment] 2021-11-03 12:05
I have the same problem. When using `conan_basic_setup(TARGETS)` each library corresponds to a target `CONAN_PKG::<library_name>` that can be individually linked, but ms-gsl is not following this convention anymore, since a few days ago.

This is likely related to [#7890](https://github.com/conan-io/conan-center-index/pull/7890).

**Comment by SpaceIm** [comment] 2021-11-03 23:46
/cc @memsharded @lasote @jgsogo @czoido

Looks like an issue in `cmake` generator preventing a smooth migration from `cpp_info.names` to `cpp_info.set_property()` (breaks consumers and will break many downstream recipes during migration).

**Comment by gummif** [comment] 2021-11-04 10:14
Constantly randomly breaking recipes is quite annoying. What is the expected used, `CONAN_PKG::Microsoft.GSL` or `CONAN_PKG::ms-gsl` or something else? Should we always use `find_package`? Is the conan center index experimental and should we always pin recipe revisions to get stability?

**Comment by SSE4** [comment] 2021-11-04 10:18
> Constantly randomly breaking recipes is quite annoying. What is the expected used, `CONAN_PKG::Microsoft.GSL` or `CONAN_PKG::ms-gsl` or something else? Should we always use `find_package`? Is the conan center index experimental and should we always pin recipe revisions to get stability?

yes, the recommendations so far are:
- `find_package` is a preferred way for the CMake integration.
- recipe revisions are recommended to use to avoid sudden breakage

**Comment by SpaceIm** [comment] 2021-11-04 10:19
For sure `find_package()` should be preferred. But `CONAN_PKG` targets in `cmake` generator shouldn't break while CCI recipe are migrated to conan v2. It might be fixed in conan 1.43: https://github.com/conan-io/conan/issues/9943#issuecomment-960572791

**Comment by SSE4** [comment] 2021-11-04 12:41
@SpaceIm we have discussed an issue internally, and we consider `set_property` affecting on the legacy `cmake` generator (`CONAN_PKG`) a breaking change. there will be a patch release (1.42.1) with the following fix: `set_property` will have no effect on this particular legacy generator.

regarding your other questions:
- `CMakeDeps` generator is not going to support `cpp_info.names` and `cpp_info.filenames`. these mechanisms are considered legacy, and `set_property` should be used instead, whenever possible. `cpp_info.name` and `cpp_info.filenames` will not exist in conan v2, and will raise an exception, if you try to access them.
- `cmake_find_package[_multi]` may get a support for the `cmake_target_namespace` in future, but it's not guaranteed right now. the main effort is aimed at `CMakeDeps` at this point. it's very desired to have `cmake_target_namespace` support for old generators, as it will allow us to do a 1 step migration, with the possibility to make recipes supporting conan 1.x and 2.x at the same time.

**Comment by dmsurti** [comment] 2021-11-08 12:08
@SSE4 Any ETA on the patch release 1.42.1?

**Comment by SSE4** [comment] 2021-11-08 12:16
> @SSE4 Any ETA on the patch release 1.42.1?

today, should be in few ours

**Comment by darcamo** [comment] 2021-11-11 19:44
Shouldn't this issue be closed?
The fix was already included in conan, and I can confirm that it is working correctly, just like before the bug was introduced.

**Closed** 2021-11-12 06:44 UTC
Labels: bug
