### ISSUE TITLE
[bug] Boost: Inconsistent visibility when using static libraries on mac

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#4093] opened 2020-12-31 16:14 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Mac OS Big Sur M1
  * Compiler+version: Apple Clang 12 (Cross-build to x86_64)
  * Conan version: 1.32
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)
[boost_static_mac_test.zip](https://github.com/conan-io/conan/files/5757653/boost_static_mac_test.zip)

See the very simple attached example which gives warnings like:
```
ld: warning: direct access in function 'boost::cpp_regex_traits<char>::get_catalog_name()' from file '/Users/rconde/.conan/data/boost/1.73.0/_/_/package/a5ae1c32fa5e7588140e7ab2ac923eca6cd85c6d/lib/libboost_regex.a(cpp_regex_traits.o)' to global weak symbol 'guard variable for boost::cpp_regex_traits<char>::get_catalog_name_inst()::s_name' from file 'CMakeFiles/boost_static_mac_test.dir/library.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

The issue is that boost builds with -fvisibility=hidden by [default](https://github.com/boostorg/build/blob/0b06096db752367ec30fd4d7f5f6df71561b13cc/src/tools/features/visibility-feature.jam).

This doesn't matter if i'm building boost as a shared library,  but when statically linking boost you will get warnings if the consuming project settings don't match. Arguably boost should switch to default visibility when building as a static library. This is something that could be argued to the boost project, or could be handled in the conan package. However, that just aligns with the most likely default. There is generally a problem here where for ANY static libraries that the visibility must match between the consumer and the consumed. It seems therefore that perhaps this should be part of the settings? Or a common option (like fPIC). I'm not sure the correct solution.

I should point out:
- This seems to be a MacOS only thing...but i'm not really sure why (I haven't tried very hard to figure that out)
- I haven't put in much effort to understand what this warning is really saying and/or if it's benign

Maybe the "fix" is just a documentation update.  In this particular case, you can get rid of the warnings by specifying:
```
"boost:extra_b2_flags": "visibility=global"
```
in your default_options.

**Comment by danimtb** [comment] 2021-01-05 12:07
@rconde01 thanks for your report. I have transferred your issue to this repo (conan-center-index) as this is the one that contains the recipes for ConanCenter.

Here you can propose a PR with the fix to the boost recipe and get some feedback from the community about it. Thanks!

**Comment by rconde01** [comment] 2021-01-05 13:53
While the example used boost, I think this is a general issue for any static library since visibility is not part of the settings. So I think the main conan repo was approporiate.

**Comment by timblechmann** [comment] 2021-01-27 03:49
having control over symbol visibility in static libraries is something that might be worth rethinking in general: when linking a static library into a shared library, one typically wants to compile the static library with hidden visibility to avoid static lib symbols to be exported from the shared lib

**Comment by axalon900** [comment] 2021-02-01 21:01
The fact that the `-fvisibility` setting doesn't factor into package ID without custom settings is quite frustrating for projects which vend their third-party dependencies by statically linking them into their dynamic library. We do this at my work for preparing dynamic frameworks for Apple platforms and I imagine it's a not-too-uncommon use case for Conan users on Mac and iOS due to the peculiarities of the platform. You can craft a profile to do it, but without a formal setting to impact the package ID it's hardly something you can rely on. And so, you have to provide your own custom setting, and once you cross the Rubicon and modify `settings.yml` you've signed up for an additional maintenance burden.

Compounding the issue is that the Mac linker is absolutely awful and has hardly any of the symbol-hiding features the Linux ELF linkers have. It's either `-fvisibility=hidden` or manually producing a whitelist or blacklist symbol file with _every individual symbol you want to show/hide_, which for C++ projects is absolutely ludicrous.

**Closed** 2021-02-04 17:11 UTC

**Comment by rconde01** [comment] 2021-02-04 17:19
This bug was changed to be specific to boost in conan-center, but it's NOT specific to boost. The fix which closes this maybe addressed the specific issue, but not the general issue. Can we open a new bug to address the general issue?

**Comment by SSE4** [comment] 2021-02-05 05:13
@rconde01 yes, please. as the title was saying boost, and your description was talking about boost specifically, I had an impression it's all about the boost. if there are more recipes affected, please open an issue.

**Comment by rconde01** [comment] 2021-02-05 05:24
@SSE4 please read the discussion in this issue. It affects ALL recipes.
