### ISSUE TITLE
[package] libjpeg/9e: ConanException: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file

### ISSUE THREAD

**Issue by sinall** [conan-io/conan-center-index#15061] opened 2023-01-02 10:31 UTC
### Description

Both libjpeg/9e and libjpeg/9d have similar error.

### Package and Environment Details

* Package Name/Version: **libjpeg/9e**
* Operating System+version: **Windows11**
* Compiler+version: **VS2022**
* Docker image: **N/A**
* Conan version: **conan 1.65.0**
* Python version: **Python 3.9.13**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=17
os=Windows
os_build=Windows
arch_build=x86_64
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

conan install . -if conaninfo/Debug --profile debug-x64 --build missing --no-imports

### Logs

<details><summary>Click to expand log</summary>

```
libjpeg/9e: Configuring sources in D:\.conan\data\libjpeg\9e\_\_\source\src
Downloading jpegsrc.v9e.tar.gz completed [4200.00k]                                      libjpeg/9e:
ERROR: libjpeg/9e: Error in source() method, line 66
        destination=self.source_folder, strip_root=True)
        ConanException: sha256 signature failed for 'jpegsrc.v9e.tar.gz' file.
 Provided signature: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
 Computed signature: 5d5349c3aacc978dfcbde11f7904d2965395261dd818ce21c15806f736b8911e
Exit code: 1
An error occurred when executing task 'ConanInstall'.
Error: One or more errors occurred. (conan install exception)
        conan install exception
```

</details>

**Comment by SpaceIm** [comment] 2023-01-02 10:58
duplicate of https://github.com/conan-io/conan-center-index/issues/15044

**Comment by uilianries** [comment] 2023-01-02 10:59
@sinall Thank you for your reporting. Please, follow the issue #15044 to keep updated.

**Closed by uilianries** 2023-01-02 10:59 UTC
Labels: bug, duplicate
