### ISSUE TITLE
[package] emsdk/3.1.72: Imported target "SDL2::SDL2-static" includes non-existent path

### ISSUE THREAD

**Issue by skhaz** [conan-io/conan-center-index#26163] opened 2024-12-11 15:08 UTC
### Description

We have a regression: it is not possible to use SDL with emsdk.

Previous versions worked, but the latest ones no longer do.

I opened an issue (link below) in the emsdk repository, and they said they have never shipped SDL with it. Therefore, there must be something in the Conan package that requires SDL, but SDL is not being included.

Reference: https://github.com/emscripten-core/emsdk/issues/1301#issuecomment-1814850196

### Package and Environment Details

* Package Name/Version: **emsdk/3.1.72**
* Operating System+version: **Any OS**
* Compiler+version: **GCC or Clang**
* Conan version: **conan latest from PyPi**
* Python version: **Python 3.12**

### Conan profile

$ cat ~/.conan2/profiles/default
[settings]
arch=armv8
build_type=Release
compiler=apple-clang
compiler.cppstd=gnu17
compiler.libcxx=libc++
compiler.version=16
os=Macos

$ cat ~/.conan2/profiles/webassembly
include(default)

[settings]
arch=wasm
os=Emscripten

[tool_requires]
*: emsdk/3.1.44

### Steps to reproduce

Use this repository, it is a MRE https://github.com/pigmentolabs/mre-sdl-and-emsdk

### Logs

```
conanfile.txt: CMakeToolchain generated: /opt/carimbo/CMakeUserPresets.json
conanfile.txt: Generating aggregated env files
conanfile.txt: Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']
Install finished successfully
-- Using Conan toolchain: /opt/carimbo/build/conan_toolchain.cmake
-- Conan toolchain: Including user_toolchain: /root/.conan2/p/b/emsdk018fc33761cad/p/bin/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
-- Conan toolchain: C++ Standard 20 with extensions OFF
-- Conan: Target declared 'OpenAL::OpenAL'
-- Conan: Including build module from '/root/.conan2/p/b/opena6096d4ee253f4/p/lib/cmake/conan-official-openal-soft-variables.cmake'
-- Conan: Target declared 'chipmunk2d::chipmunk2d'
-- Conan: Component target declared 'Ogg::ogg'
-- Conan: Target declared 'physfs-static'
-- Conan: Target declared 'spng::spng_static'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Target declared 'sol2::sol2'
-- Conan: Target declared 'lua::lua'
-- Conan: Target declared 'nlohmann_json::nlohmann_json'
-- Conan: Component target declared 'Vorbis::vorbis'
-- Conan: Component target declared 'Vorbis::vorbisenc'
-- Conan: Component target declared 'Vorbis::vorbisfile'
-- Conan: Component target declared 'vorbis::vorbisenc-alias'
-- Conan: Component target declared 'vorbis::vorbisfile-alias'
-- Conan: Target declared 'vorbis::vorbis'
-- Configuring done (0.3s)
CMake Error in CMakeLists.txt:
  Imported target "SDL2::SDL2-static" includes non-existent path

    "/root/.conan2/p/b/emsdk018fc33761cad/p/bin/upstream/emscripten/cache/sysroot/include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by SpaceIm** [comment] 2024-12-11 19:01
Isn't it a duplicate of https://github.com/conan-io/conan-center-index/issues/21131 ?

**Comment by jcar87** [comment] 2024-12-12 08:21
Closing as duplicate

**Closed by jcar87** 2024-12-12 08:21 UTC
Labels: bug
