### ISSUE TITLE
[libjpeg] libjpeg/9e: sha256 signature failed

### ISSUE THREAD

**Issue by Bobini1** [conan-io/conan-center-index#15227] opened 2023-01-12 04:50 UTC
### Description

All libjpeg recipes fail on my machine. The sha256 signatures never match.

### Package and Environment Details

* Package Name/Version: **libjpeg/9c, libjpeg/9d, libjpeg/9e**
* Operating System+version: **Linux Manjaro**
* Compiler+version: **GCC 12.2.0**
* Conan version: **conan 1.56.0**
* Python version: **Python 3.10.8**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=12
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]

### Steps to reproduce

```
def requirements(self):
    self.requires("libjpeg/9d")
```

`conan install . -s build_type=Debug -b missing`

### Logs

<details><summary>Click to expand log</summary>

```
Requirements
    libjpeg/9d from 'conancenter' - Cache
Packages
    libjpeg/9d:d13c97721d7bdc192ca6529684f2b79beeae8a7c - Build

Installing (downloading, building) binaries...
libjpeg/9d: WARN: Build folder is dirty, removing it: /home/bobini/.conan/data/libjpeg/9d/_/_/build/d13c97721d7bdc192ca6529684f2b79beeae8a7c
libjpeg/9d: WARN: Trying to remove corrupted source folder
libjpeg/9d: WARN: This can take a while for big packages
libjpeg/9d: Configuring sources in /home/bobini/.conan/data/libjpeg/9d/_/_/source/src
Downloading jpegsrc.v9d.tar.gz completed [0.44k]                                         libjpeg/9d: 
ERROR: libjpeg/9d: Error in source() method, line 65
        get(self, **self.conan_data["sources"][self.version],
        ConanException: sha256 signature failed for 'jpegsrc.v9d.tar.gz' file. 
 Provided signature: 2303a6acfb6cc533e0e86e8a9d29f7e6079e118b9de3f96e07a71a11c082fa6a  
 Computed signature: bf0502e14f0b8d7dd4e15f15b78d6f5430e4262ea2e441ce4db5f42816ca19de

```

</details>

**Comment by Croydon** [comment] 2023-01-12 10:07
Duplicate of #15186

**Comment by jcar87** [comment] 2023-01-15 18:45
Closing as duplicate - I believe this has already been fixed. Thanks for raising this issue!

**Closed by jcar87** 2023-01-15 18:45 UTC
Labels: bug
