### ISSUE TITLE
[package] multiple packages do not use their exported cmakelists.txt

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-center-index#736] opened 2020-01-27 16:01 UTC
The cmake helper of conan has a `source_folder` argument.
Some packages pass the downloaded source folder as this argument.

This might be incorrect as this can bypass `conan_basic_setup()` in the recipe's exported sources.
Unless the recipe patches the downloaded `CMakeLists.txt` of course.

A quick `grep` gives the following packages:

```
grep -Irn cmake | grep configure | grep source_folder
absent/all/conanfile.py:35:        cmake.configure(source_folder=self._source_subfolder,
amqp-cpp/all/conanfile.py:49:        cmake.configure(source_folder=self._source_subfolder)
cgal/all/conanfile.py:38:            self._cmake.configure(source_folder=self._source_subfolder)
cpp-sort/all/conanfile.py:26:        cmake.configure(source_folder=self._source_subfolder)
jasper/all/conanfile.py:46:        cmake.configure(source_folder=self._source_subfolder)
jsonformoderncpp/all/conanfile.py:37:        cmake.configure(source_folder=self._source_subfolder)
kitten/all/conanfile.py:34:        cmake.configure(source_folder=self._source_subfolder,
leptonica/all/conanfile.py:83:        cmake.configure(source_folder=self._source_subfolder)
libsolace/all/conanfile.py:52:        cmake.configure(source_folder=self._source_subfolder)
libtiff/all/conanfile.py:68:        cmake.configure(source_folder=self._source_subfolder)
minizip/1.2.11/conanfile.py:45:        cmake.configure(source_folder=self._source_subfolder)
mpfr/all/conanfile.py:61:            self._cmake.configure(source_folder=self._source_subfolder)
nlohmann_json/all/conanfile.py:34:        cmake.configure(source_folder=self._source_subfolder)
zlib/1.2.11/conanfile.py:111:            cmake.configure(source_folder=minizip_dir)
```

Hinted by @theirix,
the following packages use `CMakeListsOriginal.txt`, thus should be okay-ish.
```
grep -Irn CMakeListsOriginal | cut -f1 -d: | grep conanfile.py | uniq
amqp-cpp/all/conanfile.py
leptonica/all/conanfile.py
libmysqlclient/all/conanfile.py
libtiff/all/conanfile.py
mysql-connector-c/all/conanfile.py
poco/all/conanfile.py
```

**Comment by theirix** [comment] 2020-01-27 16:25
For several packages (leptonica, amqp-cpp, libtiff at least) it is not a bug because they do not include a whole `source_subfolder` directory but only a `CMakeListsOriginal.txt` file inside the `source_subfolder` so the source_folder must be specified in the `cmake.configure` call. You can filter out those packages by having a string CMakeListsOriginal in their conanfile.py.

**Comment by perseoGI** [comment] 2024-09-02 11:34
I'm closing this issue as it seems resolved and was opened a long time ago.
If this issue remains, do not hesitate to reopen it! 😄

**Closed by perseoGI** 2024-09-02 11:34 UTC
Labels: bug
