### ISSUE TITLE
[gdal/3.1.4]  gdal/3.1.4 does not have builds for settings: Release and options shared=True

### ISSUE THREAD

**Issue by nowgain-nowpain** [conan-io/conan-center-index#5017] opened 2021-03-23 16:02 UTC
Could you please add gdal/3.1.4 on Windows 10 and Linux builds with the following settings:
Linux:
gcc version 4.9/5/6/7/8 
build_type: Release / Debug
options: shared=True

Windows:
visual studio compiler version 14/15 (for visual studio 2015/2017)
build_type: Release / Debug
options: shared=True

Thanks you so much.

**Comment by SpaceIm** [comment] 2021-03-23 19:54
duplicate of https://github.com/conan-io/conan-center-index/issues/5017

**Closed** 2021-05-12 10:31 UTC
Labels: conan.io/center
