### ISSUE TITLE
double-conversion/3.1.5: does not compile with MSVC 2019

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#2589] opened 2020-08-18 11:49 UTC
Package and Environment Details (include every applicable attribute)
Package double-conversion/3.1.5
Operating System Windows 10
MSVC 2019
Conan version 1.28.1
Conan profile
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
*:shared=False
*:static=True
[build_requires]
[env]

### Steps to reproduce (Include if Applicable)
conan install double-conversion/3.1.5@ -r conan-center --build "*"

### Logs (Include/Attach if Applicable)
double-conversion/3.1.5: Forced build from source
Installing package: double-conversion/3.1.5
Requirements
    double-conversion/3.1.5 from 'artifactory' - Cache
Packages
    double-conversion/3.1.5:3fb49604f9c2f729b85ba3115852006824e72cab - Build

Installing (downloading, building) binaries...
double-conversion/3.1.5: WARN: Build folder is dirty, removing it: D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
double-conversion/3.1.5: Copying sources to build folder
double-conversion/3.1.5: Building your package in D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
double-conversion/3.1.5: Generator cmake created conanbuildinfo.cmake
double-conversion/3.1.5: Calling build()
double-conversion/3.1.5: WARN: CMake generator could not be deduced from settings
CMake Error: The source directory "D:/.conan/.data/double-conversion/3.1.5/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
double-conversion/3.1.5:
double-conversion/3.1.5: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
double-conversion/3.1.5: WARN: Build folder D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
ERROR: double-conversion/3.1.5: Error in build() method, line 43
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 39
        cmake.configure(build_folder=self._build_subfolder)
        ConanException: Error 1 while executing cd D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\build_subfolder && cmake -DCONAN_LINK_RUNTIME="/MD" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP4" -DCONAN_C_FLAGS="/MP4" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="D:\.conan\.data\double-conversion\3.1.5\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Wno-dev D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab

**Comment by intelligide** [comment] 2020-08-18 19:31
I can't reproduce this error.

**Comment by intelligide** [comment] 2020-08-18 19:54
Maybe forcing the recipe cache by deleting the folder `D:/.conan.data/double-conversion/3.1.5_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab` can help

**Comment by madebr** [comment] 2020-08-18 19:57
The first warning is weird:
```
WARN: CMake generator could not be deduced from settings
```
It means conan is unable to deduce from your profile that the compiler is `Visual Studio` or the compiler version or the `arch`.

Can you recheck your profile? Remove eventual trailing whitespace? (I don't know whether conan is sensitive to that)
If that doesn't work, can you try adding `CONAN_CMAKE_GENERATOR=Visual Studio 16 2019` to your profile?

Do you have cmake installed?

**Comment by AndreyMlashkin** [comment] 2020-08-18 20:13
I have cmake installed

cmake -version:
cmake version 3.18.1

I have added CONAN_CMAKE_GENERATOR, but it did not help

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
*:shared=False
*:static=True
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Visual Studio 16 2019

source folder seems really does not contain CMakeLists:

 Directory of D:\.conan\.data\double-conversion\3.1.5\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab

08/18/2020  10:08 PM    <DIR>          .
08/18/2020  10:08 PM    <DIR>          ..
08/18/2020  10:08 PM    <DIR>          build_subfolder
08/18/2020  10:08 PM            31,805 conanbuildinfo.cmake
08/17/2020  07:33 PM               170 conandata.yml
05/26/2019  01:53 AM    <DIR>          source_subfolder
               2 File(s)         31,975 bytes

**Comment by SpaceIm** [comment] 2020-08-18 20:17
Why backslash are randomly missing in your path?

**Comment by AndreyMlashkin** [comment] 2020-08-18 21:15
Removing all local recipes solved my issue, thank you!

conan remove "*" -f

**Comment by madebr** [comment] 2020-08-18 22:56
Nice! Can you please close this issue?

**Closed** 2020-08-19 04:07 UTC
Labels: bug
