### ISSUE TITLE
[package] grpc-proto/cci.20220627: "list index out of range" on build

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#15647] opened 2023-02-01 16:08 UTC
### Description

Hi conan community,

Using https://github.com/EstebanDugueperoux2/grpc_server_example example, I try to cross compile my simple project using grpc and protobuf.
It works fine without cross compilation but failed with following message in cross compilation:

```
grpc-proto/cci.20220627: Calling build()
grpc-proto/cci.20220627: 
grpc-proto/cci.20220627: ERROR: Package 'a7a777aaf7fbb80eead3cefb6f93d9f6a2e651b9' build failed
grpc-proto/cci.20220627: WARN: Build folder /home/conan/.conan/data/grpc-proto/cci.20220627/_/_/build/a7a777aaf7fbb80eead3cefb6f93d9f6a2e651b9
ERROR: grpc-proto/cci.20220627: Error in build() method, line 97
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 63
        cmake.definitions["GOOGLEAPIS_PROTO_DIRS"] = self.dependencies["googleapis"].cpp_info.resdirs[0].replace("\\", "/")
        IndexError: list index out of range
```

This seems occurs since recent commits on googleapis recipe (https://github.com/conan-io/conan-center-index/commit/97721f5322342512b93167c19bc16ed3db845dc7 or https://github.com/conan-io/conan-center-index/commit/f4a51626a07d78e616ebf9dbc68e36c4ba5489e8)

@jcar87 @coryan are you are of that issue?

Regards.

### Package and Environment Details

* Package Name/Version: **zlib/1.2.8**
* Operating System+version: **Linux Ubuntu 18.04**
* Compiler+version: **GCC 8**
* Docker image: **conanio/gcc8**
* Conan version: **conan 1.18.0**
* Python version: **Python 3.7.4**

### Conan profile

toolchain=/usr/arm-linux-gnueabihf
target_host=arm-linux-gnueabihf
cc_compiler=gcc
cxx_compiler=g++

[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$toolchain
CONAN_CMAKE_SYSROOT=$toolchain
CONAN_CMAKE_SYSTEM_NAME=Linux
CONAN_CMAKE_SYSTEM_PROCESSOR=armv7
CONAN_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=Never

CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
LD=$target_host-ld
NM=$target_host-nm
OBJCOPY=$target_host-objcopy
OBJDUMP=$target_host-objdump
RANLIB=$target_host-ranlib
STRIP=$target_host-strip

### Steps to reproduce

docker run --rm -ti -v ${PWD}:/home/conan/project conanio/gcc8-ubuntu18.04
sudo apt -y update && sudo apt install -y crossbuild-essential-armhf
cd project

conan create . --profile:build .conan/profiles/gcc8 --profile:host .conan/profiles/linux-armv7hf-gcc7 --build missing -s grpc_server_example:build_type=Debug

### Logs

<details><summary>Click to expand log</summary>

```
grpc-proto/cci.20220627: Calling build()
grpc-proto/cci.20220627: 
grpc-proto/cci.20220627: ERROR: Package 'a7a777aaf7fbb80eead3cefb6f93d9f6a2e651b9' build failed
grpc-proto/cci.20220627: WARN: Build folder /home/conan/.conan/data/grpc-proto/cci.20220627/_/_/build/a7a777aaf7fbb80eead3cefb6f93d9f6a2e651b9
ERROR: grpc-proto/cci.20220627: Error in build() method, line 97
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 63
        cmake.definitions["GOOGLEAPIS_PROTO_DIRS"] = self.dependencies["googleapis"].cpp_info.resdirs[0].replace("\\", "/")
        IndexError: list index out of range
```

</details>

**Comment by SpaceIm** [comment] 2023-02-01 18:06
duplicate of https://github.com/conan-io/conan-center-index/issues/15599, it will be fixed soon by https://github.com/conan-io/conan-center-index/pull/15451

**Closed** 2023-02-01 18:17 UTC
Labels: bug
