### ISSUE TITLE
[package] boost/1.75.0: Fails to install, due to a linux only dependancy(libunwind)

### ISSUE THREAD

**Issue by ahmadbeirkdar** [conan-io/conan-center-index#5571] opened 2021-05-20 00:21 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost/1.75.0**
  * Operating System+version: **macOS 10.15.7**
  * Compiler+version: **Apple-Clang**
  * Conan version: **conan 1.36.0*
  * Python version: **Python 3.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Install boost/1.75.0

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
boost/1.75.0: Retrieving from server 'conan-center' 
boost/1.75.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.75.0: Downloaded recipe revision 0
bzip2/1.0.8: Retrieving from server 'conan-center' 
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision 0
libbacktrace/cci.20210118: Retrieving from server 'conan-center' 
libbacktrace/cci.20210118: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libbacktrace/cci.20210118: Downloaded recipe revision 0
libunwind/1.5.0: Retrieving from server 'conan-center' 
libunwind/1.5.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libunwind/1.5.0: Downloaded recipe revision 0
ERROR: libunwind/1.5.0: Invalid configuration: libunwind is only supported on Linux and FreeBSD
CMake Error at cmake-build-macos/conan.cmake:631 (message):
  Conan install failed='6'
Call Stack (most recent call first):
  CMakeLists.txt:90 (conan_cmake_install)
```

</details>

**Comment by ahmadbeirkdar** [comment] 2021-05-20 00:45
https://github.com/conan-io/conan-center-index/commit/73b6ce44ecff5f9cedab9daf8633fc873de04d6e#diff-cc14160728d1ad321c1444ffad82615139181e681f4acb7dfd045a005cc8bd66

The following commit adds libunwind to boost

**Comment by garethsb** [comment] 2021-05-20 05:46
Duplicate of #5556

**Closed** 2021-05-23 13:31 UTC
Labels: bug
