### ISSUE TITLE
[question] When will CI build packages with gcc 10?

### ISSUE THREAD

**Issue by vvilpas** [conan-io/conan-center-index#2057] opened 2020-06-26 09:49 UTC
I have checked some recipes bumped recently (for example amqp-cpp),  and it seems there are no builds for gcc 10. When will this happen?

**Comment by Croydon** [comment] 2020-06-26 10:08
Effectively a duplicate of #1587 

But when it will happen has someone to answer from the Conan team 😄

**Comment by uilianries** [comment] 2020-06-26 19:33
Adding a new images requires a LOT of jobs, and solve all dependencies graph first. It's scheduled, but requires more people involved. @danimtb can some idea.

**Comment by danimtb** [comment] 2020-07-01 15:11
please continue the conversation in https://github.com/conan-io/conan-center-index/issues/1587

**Closed** 2020-07-01 15:11 UTC
Labels: infrastructure, question
