### ISSUE TITLE
[package] b2/4.2.0: os and arch fields appear to be missing

### ISSUE THREAD

**Issue by hannahwhy** [conan-io/conan-center-index#1733] opened 2020-05-26 04:59 UTC
The `b2/4.2.0` package does not include `os` and `arch` in its settings, which means that building `b2` for (say) two different architectures on the same OS will conflict.

The procedure below builds `b2` for both Linux x86-64 and Linux armhf.  By building the armhf package last, the `b2` x86-64 package in the local Conan cache is overwritten with a `b2` armhf package, which is not likely to be executable on an x86-64 system.

I discovered this problem while investigating hard-to-reproduce build failures in `boost` in a custom conan-center-index build system.  The current workaround is to build `b2` only for the build host OS and architecture, but this is not an easy thing to remember to do.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **b2/4.2.0**
  * Operating System+version: **Linux Ubuntu 20.04**
  * Compiler+version: **GCC 9.3.0**
  * Conan version: **conan 1.25.2**
  * Python version: **Python 3.8.2**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
Two profiles were used: one for `armhf` and one for `x86-64`.

<details>
<summary>armhf profile</summary>

```
[settings]
os=Linux
os.libc=glibc
os.libc_version=2.31
os_build=Linux
arch=armv7hf
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=arm-linux-gnueabihf-gcc-9
CXX=arm-linux-gnueabihf-g++-9
```

</details>

<details>
<summary>x86-64 profile</summary>

```

[settings]
os=Linux
os.libc=glibc
os.libc_version=2.31
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=x86_64-linux-gnu-gcc-9
CXX=x86_64-linux-gnu-g++-9
```
</details>

### Steps to reproduce (Include if Applicable)

You will need an x86-64 Linux image (Ubuntu works) that has compilers for x86-64 and armhf.  The system must not be able to execute armhf binaries via binfmt_misc.

1. Build `b2/4.2.0` with the x86-64 profile.
2. Build `b2/4.2.0` with the armhf profile.
3. Build `boost/1.73.0` or another recipe that uses `b2/4.2.0` with the x86-64 profile.
4. The `boost/1.73.0` build in step 3 will fail when it tries to invoke `b2`.

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Exporting package recipe
boost/1.73.0 exports: File 'conandata.yml' found. Exporting it...
boost/1.73.0 exports: Copied 1 '.yml' file: conandata.yml
boost/1.73.0 exports_sources: Copied 13 '.patch' files
boost/1.73.0: A new conanfile.py version was exported
boost/1.73.0: Folder: /home/user/buildAgent/temp/buildTmp/ch/.conan/data/boost/1.73.0/_/_/export
boost/1.73.0: Exported revision: 4367057d6734088108e1b305b4b38266
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os.libc=glibc
os.libc_version=2.31
os_build=Linux
[options]
qt:qtdeclarative=True
qt:qtgraphicaleffects=True
qt:qtimageformats=True
qt:qtmultimedia=True
qt:qtquickcontrols=True
qt:qtquickcontrols2=True
qt:qtsvg=True
qt:qttools=True
qt:qttranslations=True
qt:qtx11extras=True
qt:with_mysql=False
qt:with_pq=False
[build_requires]
[env]
CC=x86_64-linux-gnu-gcc-9
CXX=x86_64-linux-gnu-g++-9
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'cci-mirror'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'cci-mirror'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision 0
boost/1.73.0: Forced build from source
b2/4.2.0: Not found in local cache, looking in remotes...
b2/4.2.0: Trying with 'cci-mirror'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
b2/4.2.0: Downloaded recipe revision 0
boost/1.73.0 (test package): Installing package
Requirements
    boost/1.73.0 from local cache - Cache
    bzip2/1.0.8 from 'cci-mirror' - Downloaded
    zlib/1.2.11 from 'cci-mirror' - Downloaded
Packages
    boost/1.73.0:f405f2f5d9b494daccdf4a5637eb37b16ef2443b - Build
    bzip2/1.0.8:c9f1a709e0f221e2d4fac1f7ee192cbe9f53353c - Download
    zlib/1.2.11:4f68e1de222300d2a3484c75ac6d2d386e42feca - Download
Build requirements
    b2/4.2.0 from 'cci-mirror' - Downloaded
Build requirements packages
    b2/4.2.0:44fcf6b9a7fb86b2586303e3db40189d3b511830 - Download

Installing (downloading, building) binaries...
b2/4.2.0: Retrieving package 44fcf6b9a7fb86b2586303e3db40189d3b511830 from remote 'cci-mirror' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
b2/4.2.0: Package installed 44fcf6b9a7fb86b2586303e3db40189d3b511830
b2/4.2.0: Downloaded package revision 0
bzip2/1.0.8: Retrieving package c9f1a709e0f221e2d4fac1f7ee192cbe9f53353c from remote 'cci-mirror' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
bzip2/1.0.8: Package installed c9f1a709e0f221e2d4fac1f7ee192cbe9f53353c
bzip2/1.0.8: Downloaded package revision 0
zlib/1.2.11: Retrieving package 4f68e1de222300d2a3484c75ac6d2d386e42feca from remote 'cci-mirror' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
zlib/1.2.11: Package installed 4f68e1de222300d2a3484c75ac6d2d386e42feca
zlib/1.2.11: Downloaded package revision 0
boost/1.73.0: Applying build-requirement: b2/4.2.0
boost/1.73.0: Configuring sources in /home/user/buildAgent/temp/buildTmp/ch/.conan/data/boost/1.73.0/_/_/source

boost/1.73.0: Building your package in /home/user/buildAgent/temp/buildTmp/ch/.conan/data/boost/1.73.0/_/_/build/f405f2f5d9b494daccdf4a5637eb37b16ef2443b
boost/1.73.0: Generator txt created conanbuildinfo.txt
boost/1.73.0: Calling build()
/bin/sh: 1: b2: Exec format error
```

</details>

**Comment by Minimonium** [comment] 2020-05-26 05:08
This issue is also present in other tool packages such as CMake. I'm not sure what'll change with respect to the Contexts feature, but in the old cross-building model it's pretty much a bug. 
`os`, `arch` settings are used for consumption and they're irrelevant to the `_build` settings, which are used for building. Even if you a recipe doesn't explicitly use them - they still should be included in the `settings` field to be used in the hash generation.

**Comment by madebr** [comment] 2020-07-30 13:24
@yipdw 
https://github.com/conan-io/conan-center-index/blob/e09f9c65ca66a523668700518095abc736a910fd/recipes/b2/standard/conanfile.py#L11
4.2.0 now includes `"os", "arch"` in settings.
Also, 4.3.0 is available.

Has your problem been fixed?

**Comment by yipdw** [comment] 2020-07-30 16:08
@madebr: Thanks for the update.  I'll build `b2/4.3.0` sometime later today (let's say ~6 hours from now?) and let you know if the procedure above continues to exhibit the erroneous behavior.

**Comment by yipdw** [comment] 2020-08-03 15:37
@madebr Sorry about the delay.  The packages of `b2/4.2.0` and `b2/4.3.0` generated from the updated recipe do indeed seem to avoid the problem mentioned in this ticket.  Thanks!

**Comment by a4z** [comment] 2020-08-09 20:07
Maybe that is not the right place, but I want also to contribute m2c on the topic of cross combine tools.
It is broken and does not work.

I use cmake to build for Android and iOS, why does conan want cmake be built for Android and iOS.
And I tested putting cmake into the build_required from the --profle:build profile, but than it was not picked up at all, and the cmake from my system was used. 
So building build tools for the target os is maybe a bad idea, if not totally broken.

They should be picked up from os_build and arch_build, know nothing about os and arch, and work as advertised.

**Comment by madebr** [comment] 2020-08-09 21:58
@a4z can you create a gist with a build profile, host profile and a minimal project that reproduces your problem?
When using cmake in your build profile, I thought it should map the os of cmake to your os_build and vice versa for arch of cmake to arch_build.

**Comment by a4z** [comment] 2020-08-10 08:06
@madebr  , https://gist.github.com/a4z/39c5f4c5bdaa92d4d680032cb8e9fad3
I hope the description is sufficient, I have not found a quicker way to produce an error in a short example

I will investigate a bit more, try to print out the fill path to cmake into some log, if anyone knows how this can be done, please let me know

**Comment by a4z** [comment] 2020-08-10 08:45
I put a `print (os.environ["PATH"].split(os.pathsep))` into some recipe, run a build with 2 profiles,  and if cmake is in the --profile:build profile as build requirement, than the PATH is not set so this cmake does not exist .....
if I run the same conan create but instead of  `--profile:build buildOSX --profile:host ios64`  just with a `--profile buildOSX` then the cmake path is there.

**Comment by a4z** [comment] 2020-08-12 18:12
btw, you can forget about my comments on this ticket, turned out, everything is as it should be (since I switched to --profile:build and --profile:host) 
full explanation here: https://github.com/conan-io/conan/issues/7528
I am sorry for the noise ....

**Comment by perseoGI** [comment] 2024-09-02 16:02
Hi there! 
I'm closing this ticket as `b2/4.2.0` is no longer supported by CCI and newer versions have defined "os" and "arch" in settings.

Happy coding 🐸

**Closed by perseoGI** 2024-09-02 16:02 UTC
Labels: bug
