### ISSUE TITLE
[package] ffmpeg/6.1: x264 not found using pkg-config

### ISSUE THREAD

**Issue by 0000mz** [conan-io/conan-center-index#21694] opened 2023-12-09 15:01 UTC
### Description

When building `ffmpeg/6.1` using MSVC, ffmpeg fails to find the dependencies during the configure step. This is because the pkg-config path is not being updated to point to the generator's folder where the `*.pc` files for all the dependencies have been copied to.

A simple fix to this would be to set the `PKG_CONFIG_PATH` variable to include the generator's folder path. I have tested that this fixes the issue with this addition: https://github.com/0000mz/conan-center-index/commit/277d22fe5b3062d66371ab8211033f60bfd438c0

### Package and Environment Details

* Package Name/Version: **ffmpeg/ 6.1**
* Operating System+version: **Microsoft Windows 10 Pro 10.0.19045 N/A Build 19045**
* Compiler+version: **MSVC 193**
* Conan version: **conan 2.0.14**
* Python version: **Python 3.10.11**

### Conan profile

[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

### Steps to reproduce

```conanfile.txt
[requires]
ffmpeg/6.0

[generators]
CMakeDeps
CMakeToolchain
```

```profile.txt
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows
```

`conan install . --profile profile.txt --build=missing -c tools.cmake.cmaketoolchain:generator="Visual Studio 17 2022"`

### Logs

<details><summary>Click to expand log</summary>

```
conan install . --profile profile.txt --build=missing -c tools.cmake.cmaketoolchain:generator="Visual Studio 17 2022"

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=12
os=Windows
[conf]
tools.microsoft.bash:path=c:\Program Files\Git\bin\bash.exe
tools.microsoft.bash:subsystem=msys2


======== Computing dependency graph ========
Graph root
    conanfile.txt: C:\Users\Muiz\Documents\personal_projects\conan-ffmpeg\repro\conanfile.txt
Requirements
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    ffmpeg/6.1#014258ef8ade4ffc0a4150ce408129b9 - Cache
    libx264/cci.20220602#54f8388aa01fce20e671bfca06464c4e - Cache
    openssl/3.2.0#d81e0a8c08372368fe7cb757280e2196 - Cache
    zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
Build requirements
    meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d - Cache
    msys2/cci.latest#5a31efa2bde593541fd5ac3bcc50c01c - Cache
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
    pkgconf/2.0.3#f996677e96e61e6552d85e83756c328b - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.2.0
    zlib/[>=1.2.11 <2]: zlib/1.3

======== Computing necessary packages ========
Requirements
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d:7bde698069de06159da4d4f7bb174ecdafdbc48b#9e1829f58fdeb0444cd7ba67d21949fe - Cache
    ffmpeg/6.1#014258ef8ade4ffc0a4150ce408129b9:290df2c18738c776887ca81a1d7b8a3ea7cf54b7 - Build
    libx264/cci.20220602#54f8388aa01fce20e671bfca06464c4e:b894f9a5043b717258d8f2379a2ffdd148166387#639cf4b1c8c0ad0791b50c08a70acc32 - Cache
    openssl/3.2.0#d81e0a8c08372368fe7cb757280e2196:9027a38a34d1d55fae4f8f05ded52038ed2206e2#7b994c2b915d39a34acc489bc114ee1f - Cache
    zlib/1.3#06023034579559bb64357db3a53f88a4:ed44dacde2751b398e4bf9441ff992a70c913c00#de59ba3dad0c5ee37e780a488aaaecd3 - Cache
Build requirements
    msys2/cci.latest#5a31efa2bde593541fd5ac3bcc50c01c:956a88975bda9dfcc485e2861d71e74bd7e2b9a5#c99a611f14016fba4a51b85204f62fa3 - Cache
    pkgconf/2.0.3#f996677e96e61e6552d85e83756c328b:43771b8671ac44479c188dd72670e2eb2d7918a6#f6ed446340fdb82496318a89eb45eb01 - Cache
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694:723257509aee8a72faf021920c2874abc738e029#68bb37bc24509a0529e3363ecac8f9e3 - Cache
Skipped binaries
    meson/1.2.2, nasm/2.15.05, ninja/1.11.1, strawberryperl/5.32.1.1

======== Installing packages ========
bzip2/1.0.8: Already installed! (1 of 8)
msys2/cci.latest: Already installed! (2 of 8)
yasm/1.3.0: Already installed! (3 of 8)
yasm/1.3.0: Appending PATH environment variable: C:\Users\Muiz\.conan2\p\yasm78b751d76798d\p\bin
zlib/1.3: Already installed! (4 of 8)
libx264/cci.20220602: Already installed! (5 of 8)
pkgconf/2.0.3: Already installed! (6 of 8)
pkgconf/2.0.3: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
openssl/3.2.0: Already installed! (7 of 8)

-------- Installing package ffmpeg/6.1 (8 of 8) --------
ffmpeg/6.1: Building from source
ffmpeg/6.1: Package ffmpeg/6.1:290df2c18738c776887ca81a1d7b8a3ea7cf54b7
ffmpeg/6.1: Copying sources to build folder
ffmpeg/6.1: Building your package in C:\Users\Muiz\.conan2\p\b\ffmpe161051b358504\b
ffmpeg/6.1: Calling generate()
ffmpeg/6.1: Generators folder: C:\Users\Muiz\.conan2\p\b\ffmpe161051b358504\b\build-debug\conan
ffmpeg/6.1: Generating aggregated env files
ffmpeg/6.1: Generated aggregated env files: ['conanbuild.sh', 'conanbuild.bat']
ffmpeg/6.1: Calling build()
ffmpeg/6.1: Calling:
 > "/c/users/muiz/.conan2/p/b/ffmpe161051b358504/b/src/configure" --enable-shared --disable-static --prefix=/ --bindir=${prefix}/bin --libdir=${prefix}/lib --disable-doc --disable-cross-compile --disable-asm --enable-shared --disable-static --enable-pic --enable-avdevice --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --enable-postproc --enable-avfilter --enable-bzlib --enable-zlib --disable-lzma --disable-iconv --disable-libopenjpeg --disable-libopenh264 --disable-libvorbis --disable-libopus --disable-libzmq --disable-sdl2 --enable-libx264 --disable-libx265 --disable-libvpx --disable-libmp3lame --disable-libfdk-aac --disable-libwebp --enable-openssl --disable-alsa --disable-libpulse --disable-vaapi --disable-vdpau --disable-libxcb --disable-libxcb-shm --disable-libxcb-shape --disable-libxcb-xfixes --disable-appkit --disable-avfoundation --disable-coreimage --disable-audiotoolbox --disable-videotoolbox --disable-securetransport --disable-cuda --disable-cuvid --enable-nonfree --enable-gpl --disable-vulkan --arch=x86_64 --disable-optimizations --disable-mmx --disable-stripping --enable-debug --disable-programs --cc=cl.exe --cxx=cl.exe --pkg-config=/c/users/muiz/.conan2/p/pkgco6062a3e090f7e/p/bin/pkgconf.exe --toolchain=msvc "--extra-cflags=-MDd -Zi -Ob0 -Od" --extra-ldflags=-debug
ffmpeg/6.1: RUN: "/c/users/muiz/.conan2/p/b/ffmpe161051b358504/b/src/configure" --enable-shared --disable-static --prefix=/ --bindir=${prefix}/bin --libdir=${prefix}/lib --disable-doc --disable-cross-compile --disable-asm --enable-shared --disable-static --enable-pic --enable-avdevice --enable-avcodec --enable-avformat --enable-swresample --enable-swscale --enable-postproc --enable-avfilter --enable-bzlib --enable-zlib --disable-lzma --disable-iconv --disable-libopenjpeg --disable-libopenh264 --disable-libvorbis --disable-libopus --disable-libzmq --disable-sdl2 --enable-libx264 --disable-libx265 --disable-libvpx --disable-libmp3lame --disable-libfdk-aac --disable-libwebp --enable-openssl --disable-alsa --disable-libpulse --disable-vaapi --disable-vdpau --disable-libxcb --disable-libxcb-shm --disable-libxcb-shape --disable-libxcb-xfixes --disable-appkit --disable-avfoundation --disable-coreimage --disable-audiotoolbox --disable-videotoolbox --disable-securetransport --disable-cuda --disable-cuvid --enable-nonfree --enable-gpl --disable-vulkan --arch=x86_64 --disable-optimizations --disable-mmx --disable-stripping --enable-debug --disable-programs --cc=cl.exe --cxx=cl.exe --pkg-config=/c/users/muiz/.conan2/p/pkgco6062a3e090f7e/p/bin/pkgconf.exe --toolchain=msvc "--extra-cflags=-MDd -Zi -Ob0 -Od" --extra-ldflags=-debug
conanvcvars.bat: Activating environment Visual Studio 17 - amd64 - vcvars_ver=14.3
[vcvarsall.bat] Environment initialized for: 'x64'
mkdir: cannot create directory '/dev/shm': Read-only file system

Creating /dev/shm directory failed.
POSIX semaphores and POSIX shared memory will not work

mkdir: cannot create directory '/dev/mqueue': Read-only file system

Creating /dev/mqueue directory failed.
POSIX message queues will not work

ERROR: x264 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.

ffmpeg/6.1: ERROR:
Package '290df2c18738c776887ca81a1d7b8a3ea7cf54b7' build failed
ffmpeg/6.1: WARN: Build folder C:\Users\Muiz\.conan2\p\b\ffmpe161051b358504\b\build-debug
*********************************************************
Recipe 'ffmpeg/6.1' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: ffmpeg/6.1: Error in build() method, line 703
        autotools.configure()
        ConanException: Error 1 while executing
```

</details>

**Comment by 0000mz** [comment] 2023-12-09 15:02
I can create a pull request to upstream [the fix](https://github.com/0000mz/conan-center-index/commit/277d22fe5b3062d66371ab8211033f60bfd438c0).

**Comment by SpaceIm** [comment] 2023-12-11 19:06
`self.generators_folder` is already prepended to `PKG_CONFIG_PATH` in buildenv vars by `AutotoolsToolchain` (https://github.com/conan-io/conan/blob/2.0.14/conan/tools/gnu/autotoolstoolchain.py#L163), so I don't understand why you have this issue (there is no issue in CI, and libx264 is enabled).

**Comment by SpaceIm** [comment] 2023-12-11 19:14
```
Graph root
    conanfile.txt: C:\Users\Muiz\Documents\personal_projects\conan-ffmpeg\repro\conanfile.txt
Requirements
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    ffmpeg/6.1#014258ef8ade4ffc0a4150ce408129b9 - Cache
    libx264/cci.20220602#54f8388aa01fce20e671bfca06464c4e - Cache
    openssl/3.2.0#d81e0a8c08372368fe7cb757280e2196 - Cache
    zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
Build requirements
    meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d - Cache
    msys2/cci.latest#5a31efa2bde593541fd5ac3bcc50c01c - Cache
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
    pkgconf/2.0.3#f996677e96e61e6552d85e83756c328b - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
    yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.2.0
    zlib/[>=1.2.11 <2]: zlib/1.3
```

Which options did you disable? It's not the dependency graph when you use default options of ffmpeg recipe.

**Comment by SpaceIm** [comment] 2023-12-11 19:22
Related to https://github.com/conan-io/conan-center-index/issues/21591?

**Comment by 0000mz** [comment] 2023-12-17 12:02
> `self.generators_folder` is already prepended to `PKG_CONFIG_PATH` in buildenv vars by `AutotoolsToolchain` (https://github.com/conan-io/conan/blob/2.0.14/conan/tools/gnu/autotoolstoolchain.py#L163), so I don't understand why you have this issue (there is no issue in conancenter CI, and libx264 is enabled).

The prepending of the `PKG_CONFIG_PATH` is happening in `AutotoolsToolchain.generate()` which is only invoked for non-MSVC builds. And a quick look at the source code for [`PkgConfigDeps`](https://github.com/conan-io/conan/blob/4614b3abbff15627b3fabdd98bee419721f423ce/conan/tools/gnu/pkgconfigdeps.py#L354) shows no reference to `PKG_CONFIG_PATH`. So for MSVC builds, it will never find the right pc files.

```
if is_msvc(self):
  ...
else:
  deps = AutotoolsDeps(self)
  deps.generate()

deps = PkgConfigDeps(self)
deps.generate()
```
And this is consistent with the behavior I observed.

https://github.com/conan-io/conan-center-index/blob/d57266c3ad9eb3dbda6e369df33a0daa764a39c3/recipes/ffmpeg/all/conanfile.py#L653

> ```
> Graph root
>     conanfile.txt: C:\Users\Muiz\Documents\personal_projects\conan-ffmpeg\repro\conanfile.txt
> Requirements
>     bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
>     ffmpeg/6.1#014258ef8ade4ffc0a4150ce408129b9 - Cache
>     libx264/cci.20220602#54f8388aa01fce20e671bfca06464c4e - Cache
>     openssl/3.2.0#d81e0a8c08372368fe7cb757280e2196 - Cache
>     zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
> Build requirements
>     meson/1.2.2#aace9dcc1db58fa42ecb5292f724092d - Cache
>     msys2/cci.latest#5a31efa2bde593541fd5ac3bcc50c01c - Cache
>     nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache
>     ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
>     pkgconf/2.0.3#f996677e96e61e6552d85e83756c328b - Cache
>     strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
>     yasm/1.3.0#fb800a15413dca19bfaef9e4b5d50694 - Cache
> Resolved version ranges
>     openssl/[>=1.1 <4]: openssl/3.2.0
>     zlib/[>=1.2.11 <2]: zlib/1.3
> ```
> 
> Which options did you disable? It's not the dependency graph when you use default options of ffmpeg recipe.

Slight mistake in the conanfile.txt I posted, I am actually trying to build ffmpeg 6.1 not 6.0.

```
[requires]
ffmpeg/6.1

[generators]
CMakeDeps
CMakeToolchain
```

With that said, ran the install command again and the dependency graph is the same as in the logs I posted. 
```
> ls

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           12/9/2023  6:57 AM                .vscode
-a---           12/9/2023  6:57 AM             65 conanfile.txt
-a---           12/9/2023  6:58 AM            136 profile.txt

> cat .\conanfile.txt
[requires]
ffmpeg/6.1

[generators]
CMakeDeps
CMakeToolchain

> cat .\profile.txt
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=193
os=Windows

> conan install . --profile profile.txt --build=missing -c tools.cmake.cmaketoolchain:generator="Visual Studio 17 2022"
...
```

Looking at the default recipe, it does seem to be missing a lot of defaults, i.e. libx265 is not in the dependency graph even though it is enabled by default. Not sure why these defaults are different.

**Comment by SpaceIm** [comment] 2023-12-17 13:14
> The prepending of the PKG_CONFIG_PATH is happening in `AutotoolsToolchain.generate()` which is only invoked for non-MSVC builds.

Why do you think that? `AutotooolsToolchain.generate()` is always called in `ffmpeg` recipe, irrespective of OS, compiler or anything.

**Comment by elvisdukaj** [comment] 2024-04-04 10:17
@0000mz I wasn't able to make ffmpeg build with the suggested fix unfortunately. I am on Windows with Visual C++. The issue is the same as indicated.

I added a print of the `PKG_CONFIG_PATH` during the `generate()` and the `build()` phase to have a better view:

During the `generate()` call  `PKG_CONFIG_PATH = :/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig`
During the `build()` call  `PKG_CONFIG_PATH = /c/users/edukaj/.conan2/p/b/ffmpe575ba262ee1cf/b/build-release/conan:
`

If I `ls` in the directory I can see all the `.pc` files:

```
ls /c/users/edukaj/.conan2/p/b/ffmpe575ba262ee1cf/b/build-release/conan
SvtAv1Dec.pc                                    deactivate_msys2_mode.bat          libwebp.pc
SvtAv1Enc.pc                                    deactivate_pkgconfig_deps_path.sh  libwebpdecoder.pc
aom.pc                                          fdk-aac-fdk-aac.pc                 libwebpdemux.pc
brotli.pc                                       fdk-aac.pc                         libwebpmux.pc
bzip2.pc                                        freetype2.pc                       libx264.pc
conanautotoolsdeps_cl_workaround.sh             libbrotlicommon.pc                 msys2_mode.bat
conanautotoolstoolchain.sh                      libbrotlidec.pc                    ogg.pc
conanbuild.bat                                  libbrotlienc.pc                    openh264.pc
conanbuild.conf                                 libcpuinfo-cpuinfo.pc              openssl.pc
conanbuild.sh                                   libcpuinfo.pc                      opus.pc
conanbuildenv-release-x86_64.sh                 libcrypto.pc                       pkgconfig_deps_path.sh
conanrunenv-release-x86_64.sh                   libiconv.pc                        vorbis-all-do-not-use-vorbisenc-alias.pc
conanvcvars.bat                                 liblzma.pc                         vorbis-all-do-not-use-vorbisfile-alias.pc
dav1d.pc                                        libmp3lame.pc                      vorbis-all-do-not-use.pc
deactivate_conanautotoolsdeps_cl_workaround.sh  libopenjp2.pc                      vorbis.pc
deactivate_conanautotoolstoolchain.sh           libpng.pc                          vorbisenc.pc
deactivate_conanbuild.bat                       libpng16.pc                        vorbisfile.pc
deactivate_conanbuild.sh                        libsharpyuv.pc                     vpx.pc
deactivate_conanbuildenv-release-x86_64.sh      libssl.pc                          x264.pc
deactivate_conanrunenv-release-x86_64.sh        libsvtav1.pc                       x265.pc
deactivate_conanvcvars.bat                      libwebp-all-do-not-use.pc          zlib.pc
```

**Comment by elvisdukaj** [comment] 2024-04-04 10:36
I think I understand what is wrong finally! Inside MSYS2 I tried to set `PKG_CONFIG_PATH` to `.../b/build-release/conan` and then call `.../p/bin/pkgconf.exe --exists --print-errors 'aom >= 1.0.0'` and this works just fine.

```
$ export PKG_CONFIG_PATH=/c/users/edukaj/.conan2/p/b/ffmpe575ba262ee1cf/b/build-release/conan
$ /c/users/edukaj/.conan2/p/pkgcoe6fcefd89afdc/p/bin/pkgconf.exe --exists --print-errors 'aom >= 1.0.0'
$ echo $?
0
```

But when I do append `:` at the end of the `PKG_CONFIG_PATH` than I have the same issue:

```
$ export PKG_CONFIG_PATH=/c/users/edukaj/.conan2/p/b/ffmpe575ba262ee1cf/b/build-release/conan:
$ /c/users/edukaj/.conan2/p/pkgcoe6fcefd89afdc/p/bin/pkgconf.exe --exists --print-errors 'aom >= 1.0.0'
Package aom was not found in the pkg-config search path.
Perhaps you should add the directory containing `aom.pc'
to the PKG_CONFIG_PATH environment variable
Package 'aom', required by 'virtual:world', not found
```

**Comment by elvisdukaj** [comment] 2024-04-04 10:49
I changed the proposed patch to:

```
pkgcfg_path_env = Environment()
pkgcfg_path_env.define_path("PKG_CONFIG_PATH", self.generators_folder)
pkgcfg_path_env.vars(self, scope="build").save_script("pkgconfig_deps_path")
```

And this seems to works just fine. I will try to better understand how this variables are controlled and if I can propose a PR to fix this problem.

**Comment by elvisdukaj** [comment] 2024-04-04 12:52
I think @SpaceIm is right saying that the issue is not in `AutotoolsDeps` indeed the `PKG_CONFIG_PATH` isn't set here. The issue is instead on `AutotoolsToolchain` that is generating the wrong `PKG_CONFIG_PATH` on MSYS2.

The `PKG_CONFIG_PATH` variable is not set and using `preapend_path` is not correct.

I tested with https://github.com/conan-io/conan/pull/16016 and the build works fine again.

**Comment by jcar87** [comment] 2024-07-08 12:01
Hi @0000mz  thanks for this report.

I'm unable to reproduce this locally;
* the computed dependency graph in your build logs does not match the default options in the recipe, could you please either specify which options you have specified, or give us a minimum reproducible example?


in the build folder, please check for the presence of `conanautotoolstoolchain.sh`, this should contain the line that sets the value for `PKG_CONFIG_PATH` 

as well as the `config.log` in the build folder, which should say which value it has 

more details here for the information we need: https://github.com/conan-io/conan-center-index/issues/23309#issuecomment-2213803996

**Comment by jcar87** [comment] 2024-07-12 08:34
We have fixed an issue in the msys2 package that was causing "empty" entries in the `PKG_CONFIG_PATH` with `::` appearing in the list. 
this also explains why patches like this masked the issue: https://github.com/0000mz/conan-center-index/commit/277d22fe5b3062d66371ab8211033f60bfd438c0 - by clearing the value of PKG_CONFIG_PATH , the `::` problem was gone.

Users have confirmed that the fix in msys2 fixes this for them.

Posting a summary from our investigation in Conan Center.

* The msys2 shell gives PKG_CONFIG_PATH an initial value
* AutotoolsToolchain prepends to this value
* The resulting value on windows had something like `/c/path/to/somewhere::/path1:path2` - note the "empty" directory
This was causing issues for some user where pkgconf.exe was failing to locate libraries - users who kindly offered to troubleshoot noticed that if the empty directory in the list was gone, the call to pkgconf.exe was succeeding.

It turns out the msys2/cci.latest recipe was the "culprit" for that empty directory - in the sense that it the recipe appends to a previously existing value (which in most scenarios it's not initialised), resulting in a leading `:`, to which conan adds another one in Autotoolstoolchain.

 This is fixed in https://github.com/conan-io/conan-center-index/pull/24590
 
 Closing this issue as we believe this is now fixed if one uses the most recent revision of `msys2/cci.latest`, but please reopen it if this is not the case.

**Closed by jcar87** 2024-07-12 08:34 UTC
Labels: bug

**Comment by elvisdukaj** [comment] 2024-07-12 09:02
@jcar87 it would be great to add some test to avoid this issue in the future it could be just limited to windows + msys2.
