### ISSUE TITLE
[protobuf] protoc binary is missing in package

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan-center-index#137] opened 2019-09-30 11:12 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **protobuf/3.9.1**
  * Operating System+version: **Debian 9 (stretch) amd64**
  * Compiler+version: **gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516**
  * Conan version: **conan 1.18.5**
  * Python version: **Python 3.5.3**

### Steps to reproduce (Include if Applicable)

```
conan install protobuf/3.9.1@ -o protobuf:shared=True -o protobuf:lite=False
```
```
$ find ~/.conan/data/protobuf/3.9.1/_/_/package/b956615a2d7a652db3d8c889cd2ba264be9600c7/ -name protoc
$
```

Looks like recipe setups building of binaries:

https://github.com/conan-io/conan-center-index/blob/a34458e886d2b5c1d0e3a091a559d281644631d5/recipes/protobuf/3.9.x/conanfile.py#L57

Though final package does not have them.

Discovered while attempting to package Google ortools, and it seems it needs `protoc` in build step:
https://github.com/google/or-tools/blob/1da80508ba813ab44c1ebdedc1b37f301615df53/cmake/cpp.cmake#L157

**Comment by Talkless** [comment] 2019-09-30 11:45
I have issues trying to make `conan build` step work, to see what is actually built, before package is being made:

```
git clone https://github.com/conan-io/conan-center-index.git
cd conan-center-index/recipes/protobuf/3.9.x/
mkdir source
mkdir build
conan install . protobuf/3.9.1@ -if=build -o protobuf:shared=True -o protobuf:lite=False
conan source . -sf=source -if=build
cp -r source/* build/
conan build . -sf=source -bf=build -if=build
Using lockfile: '/home/vincas/code/opensource/conan/conan-center-index/recipes/protobuf/3.9.x/build/conan.lock'
Using cached profile from lockfile
conanfile.py (protobuf/3.9.1): Running build()
-- Conan CMake Wrapper
CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    conanbuildinfo.cmake


CMake Error at CMakeLists.txt:6 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".


-- Configuring incomplete, errors occurred!
See also "/home/vincas/code/opensource/conan/conan-center-index/recipes/protobuf/3.9.x/build/build_subfolder/CMakeFiles/CMakeOutput.log".
WARN: protobuf.patch: already patched  b'cmake/CMakeLists.txt'
WARN: protobuf.patch: already patched  b'cmake/install.cmake'
WARN: protobuf.patch: already patched  b'cmake/libprotobuf.cmake'
WARN: protobuf.patch: already patched  b'cmake/protoc.cmake'
ERROR: conanfile.py (protobuf/3.9.1): Error in build() method, line 66
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 61
	cmake.configure(build_folder=self._build_subfolder)
	ConanException: Error 1 while executing cd '/home/vincas/code/opensource/conan/conan-center-index/recipes/protobuf/3.9.x/build/build_subfolder' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="6" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCMAKE_CXX_FLAGS="-m64" -DCMAKE_SHARED_LINKER_FLAGS="-m64" -DCMAKE_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++" -DBUILD_SHARED_LIBS="ON" -DCMAKE_INSTALL_PREFIX="/home/vincas/code/opensource/conan/conan-center-index/recipes/protobuf/3.9.x/build/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Dprotobuf_BUILD_TESTS="False" -Dprotobuf_WITH_ZLIB="False" -Dprotobuf_BUILD_PROTOC_BINARIES="True" -Dprotobuf_BUILD_PROTOBUF_LITE="False" -Wno-dev '/home/vincas/code/opensource/conan/conan-center-index/recipes/protobuf/3.9.x/source'

```
Shouldn't `cmake` have `CMAKE_MODULE_PATH` and/or `CMAKE_PREFIX_PATH` arguments passed to the `-if` path? `conanbuildinfo.cmake` is actually there:
```
$ ls build/conanbuildinfo.cmake
build/conanbuildinfo.cmake
```

**Comment by uilianries** [comment] 2019-09-30 12:09
Hi @Talkless !

As you know protobuf is not only a lib, but a union of .proto files parse, cmake macros and library. If you are building your project for the same architecture (host and target), so there is no problem keeping both artifacts at same package. However, if you need to cross-compile protobuf the things are different:

- protoc (proto files parser) needs to be built for your host target (e.g. x64)
- protobuf libs needs to be built for your target arch (e.g. ARM)

But how could deal with we need different binaries on same package? We can't, so we have 2 packages for protobuf:

- protoc/3.9.1: Only the protoc
- protobuf/3.9.1: Only libs

So, if your project needs the protoc, you need to include the package `protoc/3.9.1` as `build_requires`. It will process your proto files, and will be installed following your host arch.

Now about the CMake macros ... Here we have a trick, because we can't distribute Findprotobuf.cmake twice since CMake won't load on the second time. So the protoc package has the Cmake file Findprotoc.cmake, this one is responsible by that magic macros for cmake.

**Comment by uilianries** [comment] 2019-09-30 12:13
@Talkless I just forgot that protoc is NOT available yet: https://github.com/conan-io/conan-center-index/pull/65

We are trying to find some to way to export those Cmake macros from author's cmake.

I do recommend using the protobuf from Bincrafters:

https://bintray.com/bincrafters/public-conan/protobuf%3Abincrafters/3.9.1%3Astable
https://bintray.com/bincrafters/public-conan/protoc%3Abincrafters/3.9.1%3Astable

**Comment by Talkless** [comment] 2019-09-30 12:17
> I do recommend using the protobuf from Bincrafters:

Thanks!

**Closed** 2019-09-30 12:17 UTC
Labels: question

**Comment by Talkless** [comment] 2019-09-30 12:20
@uilianries your `protoc` link does not work. There's `protoc_installer`:
https://bintray.com/bincrafters/public-conan/protoc_installer%3Abincrafters

**Comment by Talkless** [comment] 2019-09-30 12:20
@uilianries and any ideas why my local build attempt fails?

**Comment by uilianries** [comment] 2019-09-30 12:27
> @uilianries your `protoc` link does not work. There's `protoc_installer`:
> [bintray.com/bincrafters/public-conan/protoc_installer%3Abincrafters](https://bintray.com/bincrafters/public-conan/protoc_installer%3Abincrafters)

That's it, protoc_installer :+1: 

> @uilianries and any ideas why my local build attempt fails?

Let me try to reproduce your scenario. We usually use Ubuntu for our builds, maybe there is some difference from Debian.

**Comment by uilianries** [comment] 2019-09-30 22:35
@Talkless Now I see your flow. Please, read this issue: https://github.com/conan-io/conan/issues/5165

To summarize, you need to run `conan create`, the development flow `source + build + package` won't work because the patch file localization. It requires a sirurgical patch.

**Comment by Talkless** [comment] 2019-10-01 11:19
Thanks @uilianries
