### ISSUE TITLE
[package] libpq/14.5: app linked against libpq depends libpq.dll despite option libpq:shared=False

### ISSUE THREAD

**Issue by sabelka** [conan-io/conan-center-index#15301] opened 2023-01-16 13:56 UTC
### Description

I built a test app which uses libpq from conan, explicitly setting `libpq:shared=False`
Nevertheless, the generated exe requires libpq.dll to run. I would expext libpq to be built and linked statically when the option `shared` is set to `False`

Here is a minamal test project, which demonstrates the problem:

#### conanfile.txt:
```
[build_requires]

[requires]
libpq/14.5

[options]
libpq:shared=False

[generators]
virtualenv
CMakeDeps
CMakeToolchain
```

####  CMakeLists.txt
```
cmake_minimum_required(VERSION 3.24)
project(pqtest)
find_package(PostgreSQL)
add_executable(pqtest pqtest.cpp)
target_link_libraries(pqtest PRIVATE PostgreSQL::PostgreSQL)
```

#### pqtest.cpp
```
#include <libpq-fe.h>
#include <iostream>

int main()
{
    int lib_ver = PQlibVersion();
    std::cout << lib_ver << "\n";
    return 0;
}
```

### Package and Environment Details

* Package Name/Version: **libpq/14.5**
* Operating System+version: **Windows 11**
* Compiler+version: **GCC 12.2 (from mingw-builds/12.2.0)**
* Docker image: **no**
* Conan version: **conan 1.57.0**
* Python version: **Python 3.11.0**

### Conan profile

[settings]
os=Windows
arch=x86_64
build_type=Release
compiler=gcc
compiler.threads=posix
compiler.libcxx=libstdc++11
compiler.version=12
compiler.exception=seh
[options]
[conf]
[build_requires]
*: mingw-builds/12.2.0
[env]

### Steps to reproduce

`conan install .. --build=missing -pr:h=mingw -pr:b=mingw`
`activate.bat`
`cmake .. -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release`
`mingw32-make`

### Logs

<details><summary>Click to expand log</summary>

```
C:\Proj\pqtest>mkdir build

C:\Proj\pqtest>cd build

C:\Proj\pqtest\build>conan install .. --build=missing -pr:h=mingw -pr:b=mingw
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
[build_requires]
*: mingw-builds/12.2.0
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
[build_requires]
*: mingw-builds/12.2.0
[env]

conanfile.txt: Installing package
Requirements
    libpq/14.5 from 'conancenter' - Cache
Packages
    libpq/14.5:72ab1929946a1e7e9b69c00bc299eb0126492ede - Cache
Build requirements
    mingw-builds/12.2.0 from 'conancenter' - Cache
Build requirements packages
    mingw-builds/12.2.0:6903a9d1b48b06f7fbe0929db654512c77e6cc32 - Cache

Installing (downloading, building) binaries...
libpq/14.5: Already installed!
mingw-builds/12.2.0: Already installed!
mingw-builds/12.2.0: Appending PATH env var with : C:\Users\rainer\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin
conanfile.txt: Applying build-requirement: mingw-builds/12.2.0
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\Proj\pqtest\build\conan_toolchain.cmake -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.txt: Generator virtualenv created activate.bat
conanfile.txt: Generator virtualenv created deactivate.bat
conanfile.txt: Generator virtualenv created environment.bat.env
conanfile.txt: Generator virtualenv created activate.ps1
conanfile.txt: Generator virtualenv created deactivate.ps1
conanfile.txt: Generator virtualenv created environment.ps1.env
conanfile.txt: Generator virtualenv created activate.sh
conanfile.txt: Generator virtualenv created deactivate.sh
conanfile.txt: Generator virtualenv created environment.sh.env
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

C:\Proj\pqtest\build>activate.bat

(conanenv) C:\Proj\pqtest\build>cmake .. -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
-- Using Conan toolchain: C:/Proj/pqtest/build/conan_toolchain.cmake
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'libpq::pgport'
-- Conan: Component target declared 'libpq::pgcommon'
-- Conan: Component target declared 'libpq::pq'
-- Conan: Target declared 'PostgreSQL::PostgreSQL'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: C:/Proj/pqtest/build

(conanenv) C:\Proj\pqtest\build>mingw32-make
[ 50%] Building CXX object CMakeFiles/pqtest.dir/pqtest.cpp.obj
[100%] Linking CXX executable pqtest.exe
[100%] Built target pqtest

(conanenv) C:\Proj\pqtest\build>pqtest.exe    ---> cannot execute, libpq.dll not found
```

</details>

**Comment by SpaceIm** [comment] 2023-01-16 14:38
Looks like a regression coming from https://github.com/conan-io/conan-center-index/pull/14744 due to this commit: https://github.com/calebkiage/conan-center-index/commit/eeba8040d6f1a3619b76f2130e911941f6260d1b

/cc @calebkiage

**Comment by SpaceIm** [comment] 2023-01-16 15:11
It means that a .dll.a or .dll is packaged in lib folder when shared=False, but not properly removed.

**Comment by sabelka** [comment] 2023-01-16 15:44
Actually, this also happened a couple of days before #14744 was merged with libpq/14.2.

**Comment by sabelka** [comment] 2023-01-17 08:03
After googling around a bit I came to the conlusion that building libpq statically on Windows might indeed not be supported. 
https://www.mail-archive.com/pgsql-hackers@postgresql.org/msg318444.html proposes an extra target in the libpq
Makefile, but this approach seemed not so appealing for the postgres developers.

But maybe such a patch could be used in the conan package.

Or, alternatively, just use the sources of libpq and use a stripped down Makefile to build them.
Some time ago I created https://gitlab.com/sabelka/libpq-standalone exactly for this reason. The project contains a script which extracts the required files from the postgres source tree and has a CMakeLists.txt to build libpq.
This would eliminate all other dependencies (autotools, perl) too. What do you think?

**Comment by calebkiage** [comment] 2023-01-17 08:06
I'll investigate a proper fix for this. I'm looking for info on mingw static builds for postgres. I haven't found any yet.

**Comment by calebkiage** [comment] 2023-01-18 00:03
I found a fix on Fedora's package repository. I've tested all versions and they work on wine 7. Gotta love open source :-)

**Comment by sabelka** [comment] 2023-01-18 09:46
@calebkiage : I just tried the recipe from #15338 and it works! I can link against libpq and get an executable with no dependencies on libpq.dll! A big thank you!

I'll test again when the PR is available in conan remote an then close this item.

**Comment by calebkiage** [comment] 2023-01-18 10:13
Thanks for confirming! 🙂

**Comment by sabelka** [comment] 2023-01-18 12:03
Just discovered an follow up problem:
libpq comes with its own pthread emulation functions on win32.
Now that we can link statically, these functions are also exposed and lead to a conflict in applications using "the real" pthreads, leading to link errors like `multiple definition of pthread_mutex_lock`.

Do you think  postgresqlvould be configured  to use the mingw pthreads library instead (if the mingw pthhreads threading model is used)?

**Comment by calebkiage** [comment] 2023-01-19 09:35
@sabelka I'm unable to reproduce the error...what Postgres version and functions cause the error? I've connected to the postgres DB and acquired a pthread mutex lock in my test and everything worked fine.

**Comment by sabelka** [comment] 2023-01-19 13:03
@calebkiage I get the linker error only if add `set(CMAKE_EXE_LINKER_FLAGS "-static")`.

**Comment by calebkiage** [comment] 2023-01-19 15:04
> @calebkiage I get the linker error only if add `set(CMAKE_EXE_LINKER_FLAGS "-static")` in my test project.

I still don't get that issue. Can you link me to a repo that has the problem?

**Comment by sabelka** [comment] 2023-01-19 16:33
I've created a test repo here: https://github.com/sabelka/pqtest

**Comment by calebkiage** [comment] 2023-01-19 16:47
Great. I'll test it as soon as I can, but in the meantime, you can check the patch I've submitted on the [fix/libpq-mingw-static](https://github.com/calebkiage/conan-center-index/tree/fix/libpq-mingw-static) branch of my fork.

**Comment by sabelka** [comment] 2023-01-20 09:09
Tested with your fixes, the testproject compiles only if I remove the line `set(CMAKE_EXE_LINKER_FLAGS "-static")` from CMakeLists.txt, otherwise I get linker errors.

<details>
```
C:\Proj\pqtest>rebuild.bat

C:\Proj\pqtest>rmdir /s /q build-mingw-release

C:\Proj\pqtest>mkdir build-mingw-release

C:\Proj\pqtest>cd build-mingw-release

C:\Proj\pqtest\build-mingw-release>conan install .. --build=missing -pr:h=mingw -pr:b=mingw
Configuration (profile_host):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
[build_requires]
*: mingw-builds/12.2.0
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
compiler.version=12
os=Windows
[options]
[build_requires]
*: mingw-builds/12.2.0
[env]

conanfile.txt: Installing package
Requirements
    libpq/14.5 from 'conancenter' - Cache
Packages
    libpq/14.5:72ab1929946a1e7e9b69c00bc299eb0126492ede - Cache
Build requirements
    mingw-builds/12.2.0 from 'conancenter' - Cache
Build requirements packages
    mingw-builds/12.2.0:6903a9d1b48b06f7fbe0929db654512c77e6cc32 - Cache

Installing (downloading, building) binaries...
libpq/14.5: Already installed!
mingw-builds/12.2.0: Already installed!
mingw-builds/12.2.0: Appending PATH env var with : C:\Users\rainer\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin
conanfile.txt: Applying build-requirement: mingw-builds/12.2.0
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
conanfile.txt: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\Proj\pqtest\build-mingw-release\conan_toolchain.cmake -DCMAKE_SH=CMAKE_SH-NOTFOUND -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.txt: Generator virtualenv created activate.bat
conanfile.txt: Generator virtualenv created deactivate.bat
conanfile.txt: Generator virtualenv created environment.bat.env
conanfile.txt: Generator virtualenv created activate.ps1
conanfile.txt: Generator virtualenv created deactivate.ps1
conanfile.txt: Generator virtualenv created environment.ps1.env
conanfile.txt: Generator virtualenv created activate.sh
conanfile.txt: Generator virtualenv created deactivate.sh
conanfile.txt: Generator virtualenv created environment.sh.env
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

C:\Proj\pqtest\build-mingw-release>if 0 NEQ 0 exit /b 0

C:\Proj\pqtest\build-mingw-release>call activate.bat
-- Using Conan toolchain: C:/Proj/pqtest/build-mingw-release/conan_toolchain.cmake
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'libpq::pgport'
-- Conan: Component target declared 'libpq::pgcommon'
-- Conan: Component target declared 'libpq::pq'
-- Conan: Target declared 'PostgreSQL::PostgreSQL'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: C:/Proj/pqtest/build-mingw-release
[ 50%] Building CXX object CMakeFiles/pqtest.dir/pqtest.cpp.obj
[100%] Linking CXX executable pqtest.exe
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x70): multiple definition of `pthread_mutex_lock'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x70): first defined here
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x330): multiple definition of `pthread_mutex_unlock'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x90): first defined here
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-mutex.o):mutex.c:(.text+0x490): multiple definition of `pthread_mutex_init'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x30): first defined here
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x1310): multiple definition of `pthread_getspecific'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x20): first defined here
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x1380): multiple definition of `pthread_setspecific'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x10): first defined here
C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/rainer/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/lib/../lib\libpthread.a(libwinpthread_la-thread.o):thread.c:(.text+0x14b0): multiple definition of `pthread_self'; C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a(pthread-win32.o):pthread-win32.:(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [CMakeFiles\pqtest.dir\build.make:104: pqtest.exe] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/pqtest.dir/all] Error 2
mingw32-make: *** [Makefile:90: all] Error 2

(conanenv) C:\Proj\pqtest\build-mingw-release>
```
</details>

**Comment by calebkiage** [comment] 2023-01-20 09:44
I've tested with your repo and it works.
![image](https://user-images.githubusercontent.com/747955/213664600-b3999e50-3c51-49da-a8be-312965032fe6.png)

Could you try `conan remove libpq/14.5` first?

**Comment by sabelka** [comment] 2023-01-20 11:03
Mhm ... this is more or less what I did:
* I copied the `conanfile.py` from your branch to `~/.conan/data/libpq/14.5/_/_/export/conanfile.py`
* Then I removed `~/.conan/data/libpq/14.5/_/_/build/*` and `~/.conan/data/libpq/14.5/_/_/package/*`
* Then I executed my `rebuild.bat` script to rebuild my test project (I could see that PostgreSQL has been compiled the first time, I ran the script. But this is not visible in the log above, since I ran the script several times).

Maybe there is a better way to do this - but I'm not too experienced with conan.

But I'm sure this must have worked, because I get an executable statically linked to libpq (provided that I remove the `-static` linker option) which would not have happened with the original conancenter remote recipe.

The question is now what is the difference between your an my setup?
Maybe we can compare the linker command line. This is what I have:

```
C:\Users\rainer\AppData\Local\Programs\Python\Python311\Lib\site-packages\cmake\data\bin\cmake.exe -E cmake_link_script CMakeFiles\pqtest.dir\link.txt --verbose=1
C:\Users\rainer\AppData\Local\Programs\Python\Python311\Lib\site-packages\cmake\data\bin\cmake.exe -E rm -f CMakeFiles\pqtest.dir/objects.a
C:\Users\rainer\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin\ar.exe qc CMakeFiles\pqtest.dir/objects.a @CMakeFiles\pqtest.dir\objects1
C:\Users\rainer\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin\g++.exe -m64 -O3 -DNDEBUG -static -Wl,--whole-archive CMakeFiles\pqtest.dir/objects.a -Wl,--no-whole-archive -o pqtest.exe -Wl,--out-implib,libpqtest.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\pqtest.dir\linkLibs.rsp
```
And this is the content of `linkLibs.rsp` (with newlines inserted for readability):
```
C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a
-lsecur32
-ladvapi32
-lshell32
-lcrypt32
-lwldap32
C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgcommon.a
C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgcommon_shlib.a
C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgport.a
C:/Users/rainer/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgport_shlib.a
-lws2_32
-lkernel32
-luser32
-lgdi32
-lwinspool
-lshell32
-lole32
-loleaut32
-luuid
-lcomdlg32
-ladvapi32
```

**Comment by calebkiage** [comment] 2023-01-20 11:35
Sure! :-) I'm testing different scenarios on my end as well, but each build takes 30 minutes.

<details><summary>Make output</summary>

```
╰─$ mingw32-make VERBOSE=1   
"C:\Program Files\CMake\bin\cmake.exe" -SC:\Users\calebmagiya\Documents\projects\tmp\pqtest -BC:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release --check-build-system CMakeFiles\Makefile.cmake 0
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release\CMakeFiles C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release\\CMakeFiles\progress.marks
C:/Users/calebmagiya/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/mingw32-make  -f CMakeFiles\Makefile2 all
mingw32-make[1]: Entering directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
C:/Users/calebmagiya/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/mingw32-make  -f CMakeFiles\pqtest.dir\build.make CMakeFiles/pqtest.dir/depend
mingw32-make[2]: Entering directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_depends "MinGW Makefiles" C:\Users\calebmagiya\Documents\projects\tmp\pqtest C:\Users\calebmagiya\Documents\projects\tmp\pqtest C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release\CMakeFiles\pqtest.dir\DependInfo.cmake --color=
mingw32-make[2]: Leaving directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
C:/Users/calebmagiya/.conan/data/mingw-builds/12.2.0/_/_/package/6903a9d1b48b06f7fbe0929db654512c77e6cc32/bin/mingw32-make  -f CMakeFiles\pqtest.dir\build.make CMakeFiles/pqtest.dir/build
mingw32-make[2]: Entering directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
[ 50%] Building CXX object CMakeFiles/pqtest.dir/pqtest.cpp.obj
C:\Users\calebmagiya\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin\g++.exe  @CMakeFiles/pqtest.dir/includes_CXX.rsp -m64 -O3 -DNDEBUG -MD -MT CMakeFiles/pqtest.dir/pqtest.cpp.obj -MF CMakeFiles\pqtest.dir\pqtest.cpp.obj.d -o CMakeFiles\pqtest.dir\pqtest.cpp.obj -c C:\Users\calebmagiya\Documents\projects\tmp\pqtest\pqtest.cpp
[100%] Linking CXX executable pqtest.exe
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\pqtest.dir\link.txt --verbose=1
"C:\Program Files\CMake\bin\cmake.exe" -E rm -f CMakeFiles\pqtest.dir/objects.a
C:\Users\calebmagiya\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin\ar.exe qc CMakeFiles\pqtest.dir/objects.a @CMakeFiles\pqtest.dir\objects1.rsp
C:\Users\calebmagiya\.conan\data\mingw-builds\12.2.0\_\_\package\6903a9d1b48b06f7fbe0929db654512c77e6cc32\bin\g++.exe -m64 -O3 -DNDEBUG -static -Wl,--whole-archive CMakeFiles\pqtest.dir/objects.a -Wl,--no-whole-archive -o pqtest.exe -Wl,--out-implib,libpqtest.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\pqtest.dir\linklibs.rsp
mingw32-make[2]: Leaving directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
[100%] Built target pqtest
mingw32-make[1]: Leaving directory 'C:/Users/calebmagiya/Documents/projects/tmp/pqtest/build-mingw-release'
"C:\Program Files\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\calebmagiya\Documents\projects\tmp\pqtest\build-mingw-release\CMakeFiles 0
```
</details>

<details><summary>linkLibs.rsp</summary>

```
C:/Users/calebmagiya/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpq.a
-lsecur32
-ladvapi32
-lshell32
-lcrypt32
-lwldap32
-lpthread
C:/Users/calebmagiya/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgcommon.a
C:/Users/calebmagiya/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgcommon_shlib.a
C:/Users/calebmagiya/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgport.a
C:/Users/calebmagiya/.conan/data/libpq/14.5/_/_/package/72ab1929946a1e7e9b69c00bc299eb0126492ede/lib/libpgport_shlib.a
-lws2_32
-lkernel32
-luser32
-lgdi32
-lwinspool
-lshell32
-lole32
-loleaut32
-luuid
-lcomdlg32
-ladvapi32
```
</details>

**Comment by sabelka** [comment] 2023-01-20 12:38
> I noticed that your linkLibs.rsp doesn't have `-lpthread` which indicates you're using the old build.
What do you mean with "old build"? The original version from conancenter remote without your patch?
Mhm ... I doubt it, then woudn't get the error.

I tried adding `-lpthread` manually, but still got the same linker errors.
But I think linking with g++ should automatically add the pthread library (at least on minGW with the pthread thread model), so this should make no difference, actually.

Our linker arguments are otherwise the same. Then, the difference can only be in libpq.a, can it?

Let's check the file sizes:
This is libpq.a build with your patch:
```
 Verzeichnis von C:\Users\rainer\.conan\data\libpq\14.5\_\_\package\72ab1929946a1e7e9b69c00bc299eb0126492ede\lib

20.01.2023  11:44           212.208 libpq.a
               1 Datei(en),        212.208 Bytes
```

And this with the current conancenter remote:
```
 Verzeichnis von C:\Users\rainer\.conan\data\libpq\14.5\_\_\package\72ab1929946a1e7e9b69c00bc299eb0126492ede\lib

20.01.2023  13:07           117.628 libpq.a
               1 Datei(en),        117.628 Bytes
```

**Comment by calebkiage** [comment] 2023-01-20 12:44
Could you run `dumpbin /archivemembers libpq.a`?

**Comment by calebkiage** [comment] 2023-01-20 13:30
I'm sorry, I just checked and realized that I linked to the wrong branch. [fix/libpq-mingw-pthread](https://github.com/calebkiage/conan-center-index/tree/fix/libpq-mingw-pthread)

**Comment by sabelka** [comment] 2023-01-20 13:58
Great, it works! The linker errors are gone.
Thank you!

**Closed** 2023-01-20 21:08 UTC
Labels: bug
