### ISSUE TITLE
[question] How CCI deal with "Recipe and Sources in the Same Repo"? 

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan-center-index#5418] opened 2021-05-03 18:42 UTC
Hello Conan Center, 

i would like to add several packages : 

- https://github.com/eclipse-iceoryx/iceoryx/issues/764
- https://github.com/jgsogo/conan-cpptoml (because iceoryx depends on this and not saw in CCI) 
- https://github.com/eclipse-cyclonedds/cyclonedds (because i find DDS is a topic not very present in conan) 

my question now is : 

"How does the CCI deal with projects that want to keep the conanfile.py and source code side by side?" just like "Recipe and Sources in the Same Repo" on https://docs.conan.io/en/latest/creating_packages/package_repo.html

I could figure out there existing hooks to clone the repo + using "conan create ." and creating the package but all recipes i found on CCI implementing a Source Method to download source while conan processing. 
Is there no possbility in CCI to share a project which have conanfile.py on their own side by side with source code? 
like e.g. https://github.com/dotChris90/iceoryx/blob/master/conanfile.py 

thanks for anwsering. wish you a nice week.

**Comment by Croydon** [comment] 2021-05-03 19:48
Sounds like a duplicate of #22

**Comment by uilianries** [comment] 2021-05-03 21:10
> Is there no possbility in CCI to share a project which have conanfile.py on their own side by side with source code?

No.

The CCI infrastructure is implemented to get events from CCI github repo only. Also, there is a bot account which is allowed to tag issues, comment and so on.

Fetching from other repositories would include a big effort of management, CCI would need to seek a specific commit to avoid new changes, the bot would not be able to update the PR ... 

>  How CCI deal with "Recipe and Sources in the Same Repo"? 

It ignores the recipe in the upstream.

Migrating Conan recipes from github repositories to CCI is not new, it started as soon as CCI was created. You can keep your recipe there for local development, but I strongly recommend you opening a PR to CCI with a recipe which download sources and build on CCI infrastructure. The recipe will be owned by the community, you still can send fixes and improvements.

**Comment by dotChris90** [comment] 2021-05-04 05:56
@uilianries  thanks for the clearification - i still prefer the "conanfile.py" besides the source code but i can totally understand the reason for this process. Maybe i will go the 2 files approach - and just the source method differes. 

But then i close the issue. and wish you a good week ;)

**Closed** 2021-05-04 05:56 UTC
Labels: question
