### ISSUE TITLE
[package] boost/1.72.0: 82d0344 causes error on conan install

### ISSUE THREAD

**Issue by Narwhalrus** [conan-io/conan-center-index#12161] opened 2022-08-11 21:20 UTC
This commit seems to have introduced the issue: https://github.com/conan-io/conan-center-index/commit/82d034445c688df87ae7effa44023c4bd1e5d400

### Package and Environment Details

* Package Name/Version: **boost/1.72.0**
* Operating System+version: **Linux Ubuntu 20.04 LTS running under WSL2**
* Compiler+version: **GCC 9.4.0**
* Conan version: **conan 1.51.2**
* Python version: **Python 3.8.10**

### Conan profile

Configuration for profile default:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++
build_type=Release
[options]
[conf]
[build_requires]
[env]
```
### Steps to reproduce

```
$ cat conanfile.txt
[requires]
boost/1.72.0
[generators]
cmake_find_package
cmake_paths

$ conan install . --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    boost/1.72.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    libbacktrace/cci.20210118 from 'conancenter' - Cache
    zlib/1.2.12 from 'conancenter' - Cache
Packages
    boost/1.72.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed - Cache
    bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Cache
    libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
    zlib/1.2.12:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: /home/me/.conan/data/bzip2/1.0.8/_/_/package/da606cf731e334010b0bf6e85a2a6f891b9f36b0/bin
libbacktrace/cci.20210118: Already installed!
zlib/1.2.12: Already installed!
boost/1.72.0: Already installed!
ERROR: boost/1.72.0: Error in package_info() method, line 1547
        "toolset": "-{}".format(self._toolset_tag),
while calling '_toolset_tag', line 1348
        toolset_version = str(Version(self.settings.compiler.version).major(fill=False))
        TypeError: '_VersionItem' object is not callable
```

Manually replacing /home/me/.conan/data/boost/1.72.0/_/_/export/conanfile.py with the previous version resolves the issue.

### Logs

<details><summary>Click to expand log</summary>

```
Put your log output here
```

</details>

**Comment by jcar87** [comment] 2022-08-12 07:49
Hi @Narwhalrus  - many thanks for reporting this issue. We are aware of this and already have a fix in place, which we will be merging shortly after it goes through validation on CI. 

This is a duplicate of https://github.com/conan-io/conan-center-index/issues/12159, which will be updated once this is fixed.

**Closed by jcar87** 2022-08-12 07:49 UTC
Labels: bug

**Comment by Narwhalrus** [comment] 2022-08-12 14:36
Thanks. Apologies for the duplicate.
