### ISSUE TITLE
[package] gettext/0.22: MSVC debug assertions when building in Debug mode

### ISSUE THREAD

**Issue by mmomtchev** [conan-io/conan-center-index#23789] opened 2024-04-27 15:08 UTC
### Description

Building gettext/0.22 with MSVC in Debug mode produces a crash (debug assertion)

![Screenshot 2024-04-27 170319](https://github.com/conan-io/conan-center-index/assets/31410344/00bebccc-8d52-4baa-b639-988f9361c75c)

### Package and Environment Details

* Package Name/Version: **gettext/0.22**
* Operating System+version: **windows-latest (GHA)**
* Compiler+version: **MSVC 17**
* Conan version: **conan 2.2.3**
* Python version: **Python 3.12.2**

### Conan profile

```
detect_api: Found msvc 17

Detected profile:
WARN: This profile is a guess of your environment, please check it.
WARN: The output of this command is not guaranteed to be stable and can change in future Conan versions.
WARN: Use your own profile files for stability.
Saving detected profile to C:\Users\runneradmin\.conan2\profiles\default
[settings]
arch=x[8](https://github.com/mmomtchev/ImageMagick/actions/runs/8859805139/job/24329961824#step:6:9)6_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=1[9](https://github.com/mmomtchev/ImageMagick/actions/runs/8859805139/job/24329961824#step:6:10)3
os=Windows


======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows
[options]
libtype=static

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=[14](https://github.com/mmomtchev/ImageMagick/actions/runs/8859805139/job/24329961824#step:6:15)
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows
```

### Steps to reproduce

`conan install --require libgettext/0.22 -s build_type=Debug --build=missing`

### Logs

https://github.com/mmomtchev/ImageMagick/actions/runs/8859805139/job/24329961824

<details><summary>Click to expand log</summary>

```
checking whether MB_CUR_MAX is correct... yes
checking absolute name of <string.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22621.0\\ucrt\\string.h"
checking for pid_t... no
checking for mode_t... no
checking absolute name of <sys/types.h>... "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.22621.0\\ucrt\\sys/types.h"
checking whether execvpe is declared... no
checking absolute name of <unistd.h>... <unistd.h>
checking for inttypes.h... yes
checking for stdint.h... yes
checking for intmax_t... yes
checking whether snprintf returns a byte count as in C99... yes
checking whether snprintf truncates the result as in C99... yes
checking for wcslen... yes
checking for snprintf... (cached) no
checking for strnlen... yes
checking for wcrtomb... yes
checking whether _snprintf is declared... yes
checking whether printf supports size specifiers as in C99... yes
checking whether printf supports size specifiers as in C23... no
checking whether printf supports 'long double' arguments... yes
checking whether printf supports infinite 'double' arguments... yes
checking whether printf supports infinite 'long double' arguments... yes
checking whether printf supports the 'a' and 'A' directives... no
checking whether printf supports the 'b' directive... no
checking whether printf supports the 'F' directive... yes
checking whether printf supports the 'n' directive... ^CERROR: Exiting with code: 4
You pressed Ctrl+Break!
Error: The operation was canceled.
```

</details>

**Comment by Ahajha** [comment] 2024-04-28 22:19
Likely a duplicate of #23698

**Comment by mmomtchev** [comment] 2024-04-29 11:29
@Ahajha I am getting simultaneous comments with yours related to my extortion with the French police, is there a criminal message that you won't to convey?

**Closed** 2024-04-29 19:03 UTC
Labels: bug
