### ISSUE TITLE
[package] tbb/2020.0: sources hash mismatch

### ISSUE THREAD

**Issue by Shaheen47** [conan-io/conan-center-index#1174] opened 2020-03-24 12:49 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **tbb/2020.0**
  * Operating System+version: **Linux Ubuntu 19.10**
  * Compiler+version: **Clang 9.0.0**
  * Conan version: **conan 1.23.0**
  * Python version: **Python 3.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=clang
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
CC=/usr/bin/clang-9
CXX=/usr/bin/clang++-9
```

### Steps to reproduce (Include if Applicable)
put the tbb as requirement in a conanfile.txt then run 
```
 conan install .. --build=missing --profile=clang  --settings compiler.libcxx="libstdc++11" 
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
ERROR: tbb/2020.0: Error in source() method, line 55
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: sha256 signature failed for 'v2020.0.tar.gz' file. 
 Provided signature: 8eed2377ac62e6ac10af5a8303ce861e4525ffe491a061b48e8fe094fc741ce9  
 Computed signature: 57714f2d2cf33935db33cee93af57eb3ecd5a7bef40c1fb7ca4a41d79684b118

```

</details>

**Comment by danimtb** [comment] 2020-03-24 12:55
Thanks for reporting. I was able to reproduce this:

```
conan install tbb/2020.0@ --build tbb
WARN: Migration: Updating settings.yml
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

tbb/2020.0: Not found in local cache, looking in remotes...
tbb/2020.0: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.10k]
Downloading conanfile.py completed [8.60k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
tbb/2020.0: Downloaded recipe revision 6a201a530c787b438c842418b45ad80a
tbb/2020.0: Forced build from source
Installing package: tbb/2020.0
Requirements
    tbb/2020.0 from 'conan-center' - Downloaded
Packages
    tbb/2020.0:970e773c5651dc2560f86200a4ea56c23f568ff9 - Build

Installing (downloading, building) binaries...
tbb/2020.0: Configuring sources in C:\Users\danimtb\.conan\data\tbb\2020.0\_\_\source
Downloading v2020.0.tar.gz completed [2563.08k]
ERROR: tbb/2020.0: Error in source() method, line 55
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: sha256 signature failed for 'v2020.0.tar.gz' file.
 Provided signature: 8eed2377ac62e6ac10af5a8303ce861e4525ffe491a061b48e8fe094fc741ce9
 Computed signature: 57714f2d2cf33935db33cee93af57eb3ecd5a7bef40c1fb7ca4a41d79684b118
```

**Comment by danimtb** [comment] 2020-03-24 12:58
The same thing happens with ``tbb/2019_u9``

**Comment by Shaheen47** [comment] 2020-03-24 13:04
Thanks for the quick responding.
Yes indeed, However, both work fine for gcc compiler but not with Clang and visual studio as I see.
could we expect this issue to be solved quickly or it could take a long time?

**Comment by SSE4** [comment] 2020-03-24 13:11
related: #1134

**Comment by danimtb** [comment] 2020-03-24 13:13
I see this is a duplicate of #1133. Thanks @SSE4 for the hint. Please @Shaheen47 follow the conversation there!

**Closed by danimtb** 2020-03-24 13:13 UTC
Labels: bug, duplicate
