### ISSUE TITLE
[request] llvm/13.0.0

### ISSUE THREAD

**Issue by JafrinNevis** [conan-io/conan-center-index#20163] opened 2023-09-27 08:41 UTC
### Package Name/Version

llvm/13.0.0

### Changelog

https://github.com/conan-io/conan-center-index/blob/master/recipes/llvm-core/all/conanfile.py

### Context about the new update

This recipe is not working for conan version 2.0, conan v2  doesn't support the generator used here

**Comment by Croydon** [comment] 2024-06-06 05:50
Please close this as a duplicate of #20339

**Comment by uilianries** [comment] 2024-06-07 11:01
Closing this issue as duplicated. Please, commented in the issue #20339

**Closed by uilianries** 2024-06-07 11:01 UTC
Labels: duplicate, upstream update
