### ISSUE TITLE
Ninja should be compiler and build_type independent 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan-center-index#3231] opened 2020-10-17 09:07 UTC
Why does ninja depends on 
```
    settings = "os", "arch", "compiler", "build_type"
```
https://github.com/conan-io/conan-center-index/blob/4159edb0390f284ca7afedd65df7376ab3f272b9/recipes/ninja/1.10.x/conanfile.py#L11

Ninja is a build tool, it should be treated as cmake or 7zip. One package per platform, Or maybe two packages for 32 and 64 bit.

**Comment by Croydon** [comment] 2020-10-17 16:37
Effectively a duplicate of #3157 

We are discussing this right now in general

**Closed** 2020-10-29 21:01 UTC
