### ISSUE TITLE
[package] libtool/2.4.6: Invalid patches

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan-center-index#11968] opened 2022-07-29 07:09 UTC
### Package and Environment Details

* Package Name/Version: **libtool/2.4.6**
* Operating System+version: **Linux Ubuntu 20.04.4**
* Compiler+version: **GCC 10**
* Conan version: **conan 1.51.0**
* Python version: **Python 3.8.13**

### Conan profile

[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux

### Logs

<details><summary>Click to expand log</summary>

```
libtool/2.4.6: Configuring sources in /home/runner/.conan/data/libtool/2.4.6/_/_/source

libtool/2.4.6: Copying sources to build folder
libtool/2.4.6: Building your package in /home/runner/.conan/data/libtool/2.4.6/_/_/build/ae99c49d13e74caddafc3dc1668af6b86bdf63db
libtool/2.4.6: Generator txt created conanbuildinfo.txt
libtool/2.4.6: Aggregating env generators
libtool/2.4.6: Calling build()
libtool/2.4.6: 
WARN: xapian-core/1.4.18: requirement zlib/1.2.11 overridden by doxygen/1.9.4 to zlib/1.2.12 
fmt/8.1.1: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
libtool/2.4.6: ERROR: Package 'ae99c49d13e74caddafc3dc1668af6b86bdf63db' build failed
libtool/2.4.6: WARN: Build folder /home/runner/.conan/data/libtool/2.4.6/_/_/build/ae99c49d13e74caddafc3dc1668af6b86bdf63db
ERROR: libtool/2.4.6: Error in build() method, line 108
	self._patch_sources()
while calling '_patch_sources', line 101
	tools.patch(**patch)
	FileNotFoundError: [Errno 2] No such file or directory: 'patches/0001-libtool-relocatable.patch'
Error: Process completed with exit code 1.
```

</details>

See full log here: https://github.com/mpusz/units/runs/7574038282?check_suite_focus=true

**Comment by uilianries** [comment] 2022-07-29 10:44
@mpusz please, update your local cache. That patch file has been renamed recently, but still exist: https://github.com/conan-io/conan-center-index/commit/00f0dffd5b89e81fb8d2a5dfb61dbde2d4707e5a

**Comment by SpaceIm** [comment] 2022-07-29 21:31
@uilianries It's not the first time I see this kind of error when a patch is renamed. Is there a lack of robustness on conan client side? I mean, if local cache of @mpusz has the previous RREV of libtool, it should download the previous patch, and if it has latest RREV the new patch, but I don't understand what may happened in local cache to lead to this error.

**Comment by mpusz** [comment] 2022-07-30 08:40
I am still looking for a way to clear that cache on GitHub Actions so I cannot confirm if that was the source of the issue.

**Comment by uilianries** [comment] 2022-08-01 08:58
@SpaceIm it's possible there is a flaw. Indeed I saw cache problems many times, and it's not something clear for users, because both Conan behavior and output messages does not help. I could suggest to open a new issue on Conan repository, but doing a quick look, there are hundreds of issues related to "cache". Maybe, the best shot is follow and feedback on Conan 2.0, as cache stuff has been remodeled.


@mpusz One way to clear your local cache, is running `conan remove`: https://docs.conan.io/en/latest/cheatsheet.html#the-local-cache

**Comment by jgsogo** [comment] 2022-08-04 08:32
If something, this looks like an issue/improvement for the Conan client. I'm closing it here as it is not a bug in the recipe.

You know you can open an issue in Conan repository with your feedback.

Thanks!

**Closed by jgsogo** 2022-08-04 08:32 UTC
Labels: bug
