### ISSUE TITLE
[package] gdal/3.2.1: Build fails on RHEL7

### ISSUE THREAD

**Issue by rconde01** [conan-io/conan-center-index#5711] opened 2021-06-01 02:55 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: gdal/3.2.1
  * Operating System+version: Linux Redhat Enterprise Linux 7
  * Compiler+version: gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
  * Conan version: conan 1.36.0
  * Python version: 3.6.12

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os.distro=rhel7
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
From `conan-center-index/recipes/gdal/all`
```
conan create . gdal/3.2.1@/ --build missing
```
You get:
```
autoreconf: running: /home/rconde/.conan/data/autoconf/2.71/_/_/package/cb054d0b3e1ca595dc66bc2339d40f1f8f04ab31/bin/autoheader --force
autoreconf: configure.ac: not using Automake
autoreconf: './config.sub' is updated
autoreconf: './config.guess' is updated
configure.ac: error: required file 'config.rpath' not found
autoreconf: Leaving directory '.'
```

**Comment by SpaceIm** [comment] 2021-06-01 08:20
duplicate of https://github.com/conan-io/conan-center-index/issues/5707

**Closed** 2021-06-08 09:01 UTC
Labels: bug
