### ISSUE TITLE
[question] Fair Play 

### ISSUE THREAD

**Issue by Minimonium** [conan-io/conan-center-index#52] opened 2019-09-14 17:49 UTC
It'd be nice to **explicitly** state in contribution guidelines such rules that would allow Conan repository to not be against the world, but play nicely with it.

* After the [Components](https://github.com/conan-io/conan/issues/5090) feature comes in, each contribution should specify names in the `cppinfo` in accordance with the upstream project's build scripts. Would allow users of these libraries in the native build system to plug&play Conan. 

* Extending https://github.com/conan-io/conan-center-index/issues/21, we should check if there same packages in the [Vcpkg](https://github.com/microsoft/vcpkg), another fairly popular dependency manager, and name our projects the same if so (though I understand that there could be moments when we can't).

**Comment by danimtb** [comment] 2019-09-16 10:50
I think the common sense in naming is the best approach and is the summary of my answer in #23 

I understand the issue but it is not a concern right now as the `cpp_info.name` is still not there.

**Comment by gocarlos** [comment] 2019-09-16 16:38
Naming issues are actually the most problematic usage of conan in our case: we build with conan for x86 (native development) and within yocto for ARM with upstream cmake scripts (for production due to sw clearing, reproducibility etc.) , often there is a name mismatch from the exported targets from conan... 

We are at some places using cmake generator expressions to handle both cases with is suboptimal...

**Comment by danimtb** [comment] 2019-09-17 07:49
@gocarlos the issue should be mitigated by this PR in Conan https://github.com/conan-io/conan/pull/5598 where you can actually declare the "cmake name" of a library inside its recipe.

Of course, I understand naming is important and now with this repository, we can transparently discuss and fix this kind of stuff 😄

**Comment by gocarlos** [comment] 2019-09-17 12:10
@danimtb after https://github.com/conan-io/conan/pull/5598 one could start using the target names for the cmake test packages as already done for zlib (https://github.com/conan-io/conan-center-index/blob/master/recipes/zlib/1.2.11/test_package/CMakeLists.txt) test package instead of using ${CONAN_LIBS}

**Comment by danimtb** [comment] 2019-09-17 14:04
Yes, sure. That is the final goal of the feature proposed there. Hopefully, we will have it in the next Conan release

**Comment by danimtb** [comment] 2019-10-10 08:31
`self.cpp_info.name` was released in Conan 1.19. As recipes in conan-center-index run with the latest Conan, this information can be now used. Thanks

**Comment by gocarlos** [comment] 2019-10-21 07:57
is there already a way to export two targets to cmake with `self.ccp_info.name`?

e.g. my CMakeLists.txt creates two libs: `mylib::part_one` and `mylib::part_two`, tough in the generated Findmylib.cmake I only see mylib::mylib

**Comment by Minimonium** [comment] 2019-10-21 08:30
This would require the https://github.com/conan-io/conan/pull/5408

**Comment by Croydon** [comment] 2024-04-11 14:23
I think this can be closed. We have proper CMake targets and always try to follow upstream naming conventions.

And regarding naming conflicts of packages, we have a documented policy for that and there don't seem to be problems in practice so far with it.

**Closed** 2024-04-11 14:25 UTC
Labels: question
