### ISSUE TITLE
[question] Missing debug symbols

### ISSUE THREAD

**Issue by Sil3ntStorm** [conan-io/conan-center-index#11100] opened 2022-06-09 07:42 UTC
It appears as though no debug symbols for binary packages are provided. It appears as though (at least on MSVC) this will cause the compiler to not provide debug information for any static library code that depends on third party libraries pulled from conan.

```
Project A (executable)
|- Project B (static library)
   |- conan dependency
```
Project A and B are my own and project B has dependencies that are pulled in from conan.
I can debug project A just fine, however I am not able to step in to or debug any calls into project B, which is a real dealbreaker.

Is there any way we can gain the ability to debug (at least) my own code? Any reason why for debug builds there are no debug symbols provided for debug builds?

**Comment by maksim-0** [comment] 2022-06-09 08:58
See #1982

**Comment by Sil3ntStorm** [comment] 2022-06-09 11:30
It's sad to see zero progress or comments for more than 2 years on such an important issue.

**Comment by Croydon** [comment] 2022-06-10 09:30
Still a duplicate of #1982. Please close this and continue the discussion there

**Comment by uilianries** [comment] 2022-06-10 10:19
Closing it as #1982 should be used for main discussion.

**Closed by uilianries** 2022-06-10 10:19 UTC
Labels: duplicate, question
