### ISSUE TITLE
[question] Wrong arch-type in meson build command line

### ISSUE THREAD

**Issue by vithalsm** [conan-io/conan-center-index#26086] opened 2024-12-02 11:28 UTC
### What is your question?

Hi,

Trying to compile dpdk recipe (not in mainline yet) which is 'meson' based.  While cross compiling (x86_64 on x86_64), build fails.  Reason is: for cross gcc tool, **-march=x86_64** arg is being passed while it expects **-march=x86-64**.

Out conan profiles are common - used for both CMake and Meson. i.e. settings are correct and works well for CMake cross builds.  
Any clue/help on this regard is appreciated.

Snippet of error msg:
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program pkg-config found: YES
Program check-symbols.sh found: YES (/home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/src/buildtools/check-symbols.sh)
Program options-ibverbs-static.sh found: YES (/home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/src/buildtools/options-ibverbs-static.sh)
Program python3 (elftools) found: YES (/usr/bin/python3) modules: elftools
Program cat found: YES (/usr/bin/cat)
Running command: /usr/bin/cat /home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/src/ABI_VERSION
--- stdout ---
24.2

--- stderr ---

Running compile:
Working directory:  /home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/build-relwithdebinfo/meson-private/tmp6xw4hc5y
Code:
extern int i;
int i;

-----------
Command line: 

`/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-gcc -I/home/aos-dev/.conan2/p/linux406bd3fc64180/p/include /home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/build-relwithdebinfo/meson-private/tmp6xw4hc5y/testfile.c -o /home/aos-dev/.conan2/p/b/dpdk97a5832e92632/b/build-relwithdebinfo/meson-private/tmp6xw4hc5y/output.obj -c --sysroot=/usr/raicilla-sysroot -D_FILE_OFFSET_BITS=64 -O0 -march=x86_64` -> 1
stderr:
cc1: error: bad value ('x86_64') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake cooperlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 znver3 btver1 btver2 native; did you mean 'x86-64'?

-----------
Compiler for C supports arguments -march=x86_64: NO

../src/config/meson.build:186:8: ERROR: Problem encountered: Compiler does not support "x86_64" arch flag.

**Comment by vithalsm** [comment] 2024-12-02 17:06
The dpdk recipe is here: https://github.com/valgur/conan-center-index.git
Would this help?

**Comment by franramirez688** [comment] 2024-12-02 17:20
Sure! I'll take a look, thanks.

**Comment by vithalsm** [comment] 2024-12-03 04:43
> Sure! I'll take a look, thanks.

Thank you @franramirez688 !

**Comment by franramirez688** [comment] 2024-12-03 11:06
Hi @vithalsm,

I'm not able to reproduce your issue with my local profiles.
Could you share the profiles (build/host) and the Conan version you're using?

**Comment by vithalsm** [comment] 2024-12-03 11:34
Profile host:
[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=gnu14
compiler.libc=glibc
compiler.libc.version=2.34
compiler.libcxx=libstdc++
compiler.version=10.3
os=Linux
os.platform=raicilla
os.version=5.10.209
[options]
*:fPIC=True
*:shared=True
boost/*:addr2line_location=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-addr2line
dpdk/*:with_jansson=False
dpdk/*:with_libarchive=False
dpdk/*:with_libbpf=False
dpdk/*:with_openssl=False
libcurl/*:with_ntlm=False
libcurl/*:with_ntlm_wb=False
openssl/*:no_async=True
openssl/*:no_zlib=True
[conf]
tools.build.cross_building:can_run=False
tools.build.cross_building:cross_build=True
tools.build:skip_test=True
tools.build:sysroot=/usr/raicilla-sysroot
tools.cmake.cmake_layout:build_folder_vars=['settings.os.platform']
tools.gnu:host_triplet=x86_64-aruba-linux-gnu
[buildenv]
CONAN_CMAKE_FIND_ROOT_PATH=/usr/x86-10.3-glibc-2.34
CONAN_CMAKE_SYSROOT=/usr/raicilla-sysroot
CC=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-gcc
CXX=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-g++
STRIP=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-strip
AR=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-ar
AS=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-as
LD=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-ld
RANLIB=/usr/x86-10.3-glibc-2.34/bin/x86_64-aruba_buildroot-linux-gnu-ranlib

Profile build:
[settings]
arch=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=gnu14
compiler.libc=glibc
compiler.libc.version=2.31
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os.platform=native
os.version=5.15
[options]
*:fPIC=True
*:shared=True
libcurl/*:with_ntlm=False
libcurl/*:with_ntlm_wb=False
openssl/*:no_async=True
openssl/*:no_zlib=True
[conf]
tools.build:compiler_executables={'c': '/usr/bin/gcc'}
tools.cmake.cmake_layout:build_folder_vars=['settings.os.platform']

**Comment by vithalsm** [comment] 2024-12-03 15:45
Hi @franramirez688 Sure, let me try and see if I can figure out any better way.

So, is cross compilation going through fine for you?  If so, can you plz send me the build log, I can look and compare.

Couple of things:
1) Issue is pertaining to conan + meson: likely conan generating command lines for meson.  
2) For CMAke Too Chain, I see function like: architecture_flag() which is called during toolchain init.  Which seems to adjust 'arch' flags (from x86_64 to -m64 or something). 
   For MesanToolChain, I don't really see any such calls/actions.
3) gcc -march=x86_64 test.c : produces exactly same error.

**Comment by vithalsm** [comment] 2024-12-03 15:50
Attaching meson build log if it helps in anyway.

[meson-log.txt](https://github.com/user-attachments/files/17995558/meson-log.txt)

**Comment by vithalsm** [comment] 2024-12-04 04:38
Ok.  Following are the exact steps that reproduced.
1) git clone [the repo](https://github.com/valgur/conan-center-index.git).  'dpdk' is of interest.
2) Have build and host profiles as listed above.  (toolchains to be adjusted accordingly to existing ones)
    . say prof-bld and prof-host
3) go to recipe/dpdk/all folder.
4) Run the following commands:
    - conan source . --name dpdk --version 24.07
    - conan build . -pr:h prof-bld -pr:b prof-host  --build=missing
5) Now the problem is certain to be hit.

**Comment by franramirez688** [comment] 2024-12-05 06:24
Hi @vithalsm 

Thanks a lot for all the steps provided 😁 Finally, we got to reproduce the issue 👏 

```bash
Program check-symbols.sh found: YES (/root/.conan2/p/b/dpdk7fd5db364557b/b/src/buildtools/check-symbols.sh)
Program options-ibverbs-static.sh found: YES (/root/.conan2/p/b/dpdk7fd5db364557b/b/src/buildtools/options-ibverbs-static.sh)
Program python3 (elftools) found: YES (/root/.conan2/p/b/cpyth50686e99ad2eb/p/bin/python3) modules: elftools
Program cat found: YES (/usr/bin/cat)
Compiler for C supports arguments -march=x86_64: NO 

../src/config/meson.build:186:8: ERROR: Problem encountered: Compiler does not support "x86_64" arch flag.
```

The problem is a bug in the upstream repository:

https://github.com/DPDK/dpdk/blob/7df61db6c387703a36306c1aea92225921e2eeb2/config/meson.build#L117
https://github.com/DPDK/dpdk/blob/7df61db6c387703a36306c1aea92225921e2eeb2/config/meson.build#L179

There, we can see these lines:

```python
# set the cpu_instruction_set and cflags for it
if meson.is_cross_build()
    cpu_instruction_set = host_machine.cpu()
else:
    # ...
# .....

if not is_ms_compiler
    # ppc64 does not support -march= at all, use -mcpu and -mtune for that
    if host_machine.cpu_family().startswith('ppc')
        # ....
    else
        machine_args += '-march=' + cpu_instruction_set
```

The Conan arch mapping is fine and follows the meson one: https://mesonbuild.com/Reference-tables.html#cpu-families
but upstream seems that it never tried to cross-compile toward an x86_64 arch.

Then, as a non-elegant/fast workaround, you could add  within the dpdk's `build()` function these lines:

```python
    def build(self):
        self._pip_install(["pyelftools"])
        if self.settings.arch == "x86_64" and cross_building(self):
            replace_in_file(self, os.path.join(self.source_folder, "config/meson.build"), "cpu_instruction_set = host_machine.cpu()", "cpu_instruction_set = 'x86-64'")
        meson = Meson(self)
        meson.configure()
        meson.build()
```

That should do the trick 🤞

**Comment by vithalsm** [comment] 2024-12-05 16:26
Thanks @franramirez688.
I had done changes in meson.build and created a 'patch' file instead to set cpu_instruction_set=x86-64.  
However, was unsure, whether its conan tool chain which should handle similar to CMake architecture_flag.  If you think, its dpdk which has to handle, then will raise a bug against it.

BTW, did the build go through for you?  Or hit issue related to 'numa' lib not found?  (Due to wrong 'paths' being constructed for -I and -L)

**Comment by jcar87** [comment] 2024-12-05 17:44
> . If you think, its dpdk which has to handle, then will raise a bug against it.

We think this is an issue of `dpdk`, where they are mapping the `host_machine.cpu()` value returned by meson, directly to the `-march=` flag for the compiler. From what we've seen, meson uses `x86_64`, and the compiler expects `x86-64`. I believe this is not an issue they have encountered because it is "less frequent" to cross-build with x86_64 as the target - so it sounds like reaching out to the upstream maintainers would be a good place to start.

**Comment by vithalsm** [comment] 2024-12-06 04:05
Sure, will take it forward accordingly.  Thanks very much @franramirez688 and @jcar87 for the help.

Well, for next issue, related to incorrect paths, where <sysroot> path is prepended with dependency lib and inc path, should I be raising new case?  May be something similar to https://github.com/conan-io/conan/pull/17257 - but with CMake.

From build logs, you could the INC and LIB paths as:

-I**/usr/myplat-sysroot**/home/aos-dev/.conan2/p/b/libnuc9aea6f2a39ea/p/include
-L**/usr/myplat-sysroot**/home/aos-dev/.conan2/p/b/libnuce8753089a969/p/lib
--sysroot=/usr/myplat-sysroot.

Please let me.

**Comment by franramirez688** [comment] 2024-12-12 17:06
Hi @vithalsm 

> Well, for next issue, related to incorrect paths, where path is prepended with dependency lib and inc path, should I be raising new case? May be something similar to https://github.com/conan-io/conan/pull/17257 - but with CMake.

Yes, you should open a new issue for that as it's related to a very different topic. Let's look at the logs and all the important information to understand the problem.

Thanks a lot for your efforts 😁 

By the way, you can close this issue as it seems solved (waiting for the upstream issue/PR).

**Closed** 2024-12-16 06:03 UTC
Labels: question
