### ISSUE TITLE
pcre2/10.37 fails to build on Raspberry Pi

### ISSUE THREAD

**Issue by matte86** [conan-io/conan-center-index#8002] opened 2021-11-09 12:02 UTC
Hey guys,

I am trying to build Qt 5.15.2 for the Raspberry Pi. Somehow it fails on the pcre2 dependency with the log attached below.
I am pretty sure it used to work in the past. I had to empty my local conan cache so qt is rebuilding from sources. However I never had this issue. Is anyone experiencing the same?

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **pcre2/10.37**
  * Operating System+version: **Raspbian GNU/Linux 10 (buster)**
  * Compiler+version: **Raspbian 8.3.0-6+rpi1**
  * Conan version: **conan 1.41.0**
  * Python version: **Python 3.7.4**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=armv7
arch_build=armv7
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
Build a simple application with qt

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
Installing (downloading, building) binaries...
brotli/1.0.9: Already installed!
bzip2/1.0.8: Already installed!
bzip2/1.0.8: Appending PATH environment variable: /home/pi/.conan/data/bzip2/1.0.8/_/_/package/9389a4c2c70b5b37c341b3cae252e60bdd643714/bin
double-conversion/3.1.5: Already installed!
expat/2.4.1: Already installed!
gnu-config/cci.20201022: Already installed!
gnu-config/cci.20201022: Appending PATH environment variable: /home/pi/.conan/data/gnu-config/cci.20201022/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
gperf/3.1: Already installed!
gperf/3.1: Appending PATH environment variable: /home/pi/.conan/data/gperf/3.1/_/_/package/ef8d7bb63b73bcc98204f8763adba33115db9de2/bin
gtest/1.11.0: Already installed!
icu/69.1: Already installed!
icu/69.1: Appending ICU_DATA environment variable: /home/pi/.conan/data/icu/69.1/_/_/package/a31ff4d530dd749753546fdb903a836fc7b09c0b/res/icudt69l.dat
icu/69.1: Appending PATH environment variable: /home/pi/.conan/data/icu/69.1/_/_/package/a31ff4d530dd749753546fdb903a836fc7b09c0b/bin
libffi/3.4.2: Already installed!
libiconv/1.16: Already installed!
libiconv/1.16: Appending PATH environment var: /home/pi/.conan/data/libiconv/1.16/_/_/package/d458f0ad17daab8c37a59b910c7b82677fd9d3c0/bin
libjpeg/9d: Already installed!
m4/1.4.19: Already installed!
m4/1.4.19: Appending PATH environment variable: /home/pi/.conan/data/m4/1.4.19/_/_/package/ef8d7bb63b73bcc98204f8763adba33115db9de2/bin
m4/1.4.19: Setting M4 environment variable: /home/pi/.conan/data/m4/1.4.19/_/_/package/ef8d7bb63b73bcc98204f8763adba33115db9de2/bin/m4
m4/1.4.19: Appending PATH environment variable: /home/pi/.conan/data/m4/1.4.19/_/_/package/ef8d7bb63b73bcc98204f8763adba33115db9de2/bin
m4/1.4.19: Setting M4 environment variable: /home/pi/.conan/data/m4/1.4.19/_/_/package/ef8d7bb63b73bcc98204f8763adba33115db9de2/bin/m4
ninja/1.10.2: Already installed!
nlohmann_json/3.10.4: Already installed!
opengl/system: Already installed!
pkgconf/1.7.4: Already installed!
pkgconf/1.7.4: Appending PATH env var: /home/pi/.conan/data/pkgconf/1.7.4/_/_/package/d458f0ad17daab8c37a59b910c7b82677fd9d3c0/bin
pkgconf/1.7.4: Setting PKG_CONFIG env var: /home/pi/.conan/data/pkgconf/1.7.4/_/_/package/d458f0ad17daab8c37a59b910c7b82677fd9d3c0/bin/pkgconf
pkgconf/1.7.4: Appending AUTOMAKE_CONAN_INCLUDES env var: /home/pi/.conan/data/pkgconf/1.7.4/_/_/package/d458f0ad17daab8c37a59b910c7b82677fd9d3c0/bin/aclocal
serial/1.2.1: Already installed!
wayland-protocols/1.21: Already installed!
xorg/system: Already installed!
zlib/1.2.11: Already installed!
zstd/1.5.0: Already installed!
autoconf/2.71: Already installed!
autoconf/2.71: Appending PATH env var with : /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
autoconf/2.71: Setting AC_MACRODIR to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/share/autoconf
autoconf/2.71: Setting AUTOCONF to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoconf
autoconf/2.71: Setting AUTORECONF to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoreconf
autoconf/2.71: Setting AUTOHEADER to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autoheader
autoconf/2.71: Setting AUTOM4TE to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/autom4te
autoconf/2.71: Setting AUTOM4TE_PERLLIBDIR to /home/pi/.conan/data/autoconf/2.71/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/share/autoconf
flex/2.6.4: Already installed!
flex/2.6.4: Appending PATH environment variable: /home/pi/.conan/data/flex/2.6.4/_/_/package/1a2164423f0da5488467c4ddcbc3ad29cd8eb2d3/bin
flex/2.6.4: Setting LEX environment variable: /home/pi/.conan/data/flex/2.6.4/_/_/package/1a2164423f0da5488467c4ddcbc3ad29cd8eb2d3/bin/flex
libpng/1.6.37: Already installed!
libxml2/2.9.12: Already installed!
libxml2/2.9.12: Appending PATH environment variable: /home/pi/.conan/data/libxml2/2.9.12/_/_/package/0da3e8420b5f6a4bb43b965855158b2b617b4e6f/bin
meson/0.59.1: Already installed!
meson/0.59.1: Appending PATH environment variable: /home/pi/.conan/data/meson/0.59.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
meson/0.59.1: Appending PATH environment variable: /home/pi/.conan/data/meson/0.59.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin
pcre2/10.37: WARN: Build folder is dirty, removing it: /home/pi/.conan/data/pcre2/10.37/_/_/build/436bf2144f4b4ac529aec8ef5a66e1746ab8934a
pcre2/10.37: WARN: Trying to remove corrupted source folder
pcre2/10.37: WARN: This can take a while for big packages
pcre2/10.37: Configuring sources in /home/pi/.conan/data/pcre2/10.37/_/_/source
ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre2-10.37.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xb50aab90>, 'Connection to ftp.pcre.org timed out. (connect timeout=60.0)'))'
Waiting 5 seconds to retry...
ERROR: pcre2/10.37: Error in source() method, line 77
	destination=self._source_subfolder, strip_root=True)
	ConanException: Error downloading file https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre2-10.37.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xb503f050>, 'Connection to ftp.pcre.org timed out. (connect timeout=60.0)'))'
```

</details>

**Comment by SpaceIm** [comment] 2021-11-09 12:06
Duplicate of https://github.com/conan-io/conan-center-index/issues/7963. Previous Source url is not longer available, a mirror has been added in pcre2 recipe.

**Closed** 2021-11-09 12:33 UTC
Labels: bug
