### ISSUE TITLE
[package] aws-c-common/0.8.2: sha256 signature failed

### ISSUE THREAD

**Issue by msd97** [conan-io/conan-center-index#15574] opened 2023-01-30 21:08 UTC
### Description

The signature check for package aws-c-common fails with the following error:

```
ERROR: aws-c-common/0.8.2: Error in source() method, line 66
        get(self, **self.conan_data["sources"][self.version],
        ConanException: sha256 signature failed for 'v0.8.2.tar.gz' file. 
 Provided signature: 36edc6e486c43bbb34059dde227e872c0d41ab54f0b3609d38f188cfbbc6d1f8  
 Computed signature: d4ace07b084b46aa30542948556326233f49d8a5a132bcde3035e7f58f7662e1
```

### Package and Environment Details

* Package Name/Version: **aws-c-common/0.8.2**
* Operating System+version: **Linux Ubuntu 20.04.1**
* Compiler+version: **GCC 9**
* Docker image: **custom**
* Conan version: **conan 1.58.0**
* Python version: **Python 3.8.10**

### Conan profile

[settings]
os=Linux
arch=armv8
compiler=gcc
compiler.version=9.4
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
tools.build:compiler_executables.c=$cross_compiler-gcc
tools.build:compiler_executables.cpp=$cross_compiler-g++
tools.build:cflags=["-L/usr/aarch64-linux-gnu/include/", "-DCMAKE_SYSTEM_NAME=Linux", "-DCMAKE_SYSTEM_PROCESSOR=armv8", "-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc", "-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++", "-DCMAKE_CPP_COMPILER=aarch64-linux-gnu-cpp"]
tools.build:cxxflags=["-L/usr/aarch64-linux-gnu/include/","-DCMAKE_SYSTEM_NAME=Linux", "-DCMAKE_SYSTEM_PROCESSOR=armv8", "-DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc", "-DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++", "-DCMAKE_CPP_COMPILER=aarch64-linux-gnu-cpp"]
[build_requires]
[env]

### Steps to reproduce

1. Attempt installation of aws-c-common 0.8.2
2. It will fail showing the provided log in the description

### Logs

<details><summary>Click to expand log</summary>

```
aws-c-common/0.8.2: Configuring sources in /root/.conan/data/aws-c-common/0.8.2/_/_/source/src
Downloading v0.8.2.tar.gz completed [484.50k]                                            aws-c-common/0.8.2: 2: 
ERROR: aws-c-common/0.8.2: Error in source() method, line 66
        get(self, **self.conan_data["sources"][self.version],
        ConanException: sha256 signature failed for 'v0.8.2.tar.gz' file. 
 Provided signature: 36edc6e486c43bbb34059dde227e872c0d41ab54f0b3609d38f188cfbbc6d1f8  
 Computed signature: d4ace07b084b46aa30542948556326233f49d8a5a132bcde3035e7f58f7662e1
Conan installation failed. Exitting...
```

</details>

**Comment by Ahajha** [comment] 2023-01-30 21:14
Duplicate of https://github.com/conan-io/conan-center-index/issues/15571 - It seems any .tar.gz file is affected.

**Comment by camm73** [comment] 2023-01-30 22:30
Looks like the change is being rolled back: https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954

**Comment by Croydon** [comment] 2023-01-30 23:52
Please close as duplicate of #15571

**Closed** 2023-01-30 23:53 UTC
Labels: bug
