### ISSUE TITLE
[question] how to use CCI qt recipe? 

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-center-index#5450] opened 2021-05-06 08:08 UTC
I am currently using an old qt recipe qt/5.15.2@bincrafters/stable and I would like to switch to qt/5.15.2.
here is how I am going to use new recipe, based on what I have seen in test_package:
```
-find_package(Qt5Widgets REQUIRED)
-find_package(Qt5Gui REQUIRED)
-find_package(Qt5Network REQUIRED)
-find_package(Qt5OpenGL REQUIRED)
-find_package(Qt5Concurrent REQUIRED)
+find_package(qt REQUIRED CONFIG)

 set(LIBS
-  ${Qt5Widgets_LIBRARIES}
-  ${Qt5Gui_LIBRARIES}
-  ${Qt5Network_LIBRARIES}
-  ${Qt5OpenGL_LIBRARIES}
-  ${Qt5Concurrent_LIBRARIES}
+  qt::qt
 )

target_link_libraries(${PROJECT_NAME} ${LIBS})
```

I am still getting an error:
```
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /home/andrei/sources/build_studio_clang_vulkan
-- Conan: Compiler Clang>=8, checking major version 10
-- Conan: Checking correct version: 10
CMake Error at CMakeLists.txt:96 (find_package):
  Could not find a package configuration file provided by "qt" with any of
  the following names:

    qtConfig.cmake
    qt-config.cmake

  Add the installation prefix of "qt" to CMAKE_PREFIX_PATH or set "qt_DIR" to
  a directory containing one of the above files.  If "qt" provides a separate
  development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/andrei/sources/build_studio_clang_vulkan/CMakeFiles/CMakeOutput.log".
```

What I am doing wrong here?

**Comment by ericLemanissier** [comment] 2021-05-06 08:11
your conanfile is probably missing the `cmake_find_package_multi` generator ?

**Comment by AndreyMlashkin** [comment] 2021-05-06 09:10
Yes, it is missing. But when I have added it, nothing changed...

**Comment by AndreyMlashkin** [comment] 2021-05-06 09:32
Wait. It helped, it fails somewhere else now. Thank you!

**Comment by AndreyMlashkin** [comment] 2021-05-06 10:33
It is now failing while linking... maybe you have a hint for me?

...
'''
[100%] Linking CXX executable bin/PictofitStudio
/usr/bin/ld: /home/andrei/.conan/data/qt/5.15.2/_/_/package/44c5573505e7976c7c5e4a0a2cfedf9f1678964c/lib/libQt5Gui.a(qopenglpaintengine.o): in function `QOpenGL2PaintEngineExPrivate::drawPixmapFragments(QPainter::PixmapFragment const*, int, QPixmap const&, QFlags<QPainter::PixmapFragmentHint>)':
qopenglpaintengine.cpp:(.text._ZN28QOpenGL2PaintEngineExPrivate19drawPixmapFragmentsEPKN8QPainter14PixmapFragmentEiRK7QPixmap6QFlagsINS0_18PixmapFragmentHintEE+0x129): undefined reference to `qt_sine_table'
/usr/bin/ld: /home/andrei/.conan/data/qt/5.15.2/_/_/package/44c5573505e7976c7c5e4a0a2cfedf9f1678964c/lib/libQt5Gui.a(qtriangulatingstroker.o): in function `QTriangulatingStroker::process(QVectorPath const&, QPen const&, QRectF const&, QFlags<QPainter::RenderHint>)':
qtriangulatingstroker.cpp:(.text._ZN21QTriangulatingStroker7processERK11QVectorPathRK4QPenRK6QRectF6QFlagsIN8QPainter10RenderHintEE+0x261): undefined reference to `qt_sine_table'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/PictofitStudio.dir/build.make:6359: bin/PictofitStudio] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/PictofitStudio.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
'''

as I understand, I should not include/link additional qt modules separately in CMake, right?

**Comment by AndreyMlashkin** [comment] 2021-05-06 10:40
And here what I've got for Mac:
'''
[100%] Linking CXX executable bin/PictofitStudio
Undefined symbols for architecture x86_64:
  "_SCDynamicStoreCopyProxies", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt5Network.a(qnetconmonitor_darwin.o)
  "_SCNetworkReachabilityCreateWithAddressPair", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt5Network.a(qnetconmonitor_darwin.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt5Network.a(qnetconmonitor_darwin.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      QNetworkConnectionMonitor::~QNetworkConnectionMonitor() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkConnectionMonitor::stopMonitoring() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkConnectionMonitor::startMonitoring() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkStatusMonitor::~QNetworkStatusMonitor() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkStatusMonitor::stop() in libQt5Network.a(qnetconmonitor_darwin.o)
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      QNetworkConnectionMonitor::~QNetworkConnectionMonitor() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkConnectionMonitor::stopMonitoring() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkConnectionMonitor::startMonitoring() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkStatusMonitor::~QNetworkStatusMonitor() in libQt5Network.a(qnetconmonitor_darwin.o)
      QNetworkStatusMonitor::stop() in libQt5Network.a(qnetconmonitor_darwin.o)
  "___gss_c_nt_hostbased_service_oid_desc", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt5Network.a(qauthenticator.o)
  "_gss_acquire_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<QPair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt5Network.a(qauthenticator.o)
  "_gss_delete_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt5Network.a(qauthenticator.o)
  "_gss_display_status", referenced from:
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt5Network.a(qauthenticator.o)
  "_gss_import_name", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt5Network.a(qauthenticator.o)
  "_gss_init_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt5Network.a(qauthenticator.o)
  "_gss_release_buffer", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt5Network.a(qauthenticator.o)
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt5Network.a(qauthenticator.o)
  "_gss_release_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<QPair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt5Network.a(qauthenticator.o)
  "_gss_release_name", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<QPair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt5Network.a(qauthenticator.o)
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt5Network.a(qauthenticator.o)
  "_kSCPropNetProxiesExceptionsList", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesExcludeSimpleHostnames", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesFTPEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesFTPPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesFTPProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPSEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPSPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesHTTPSProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesProxyAutoConfigEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesProxyAutoConfigURLString", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesSOCKSEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesSOCKSPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
  "_kSCPropNetProxiesSOCKSProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt5Network.a(qnetworkproxy_mac.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/PictofitStudio] Error 1
make[1]: *** [CMakeFiles/PictofitStudio.dir/all] Error 2
make: *** [all] Error 2
'''

**Comment by jt416** [comment] 2021-05-11 14:15
I am working through a similar use case (and problems). Today, I see that the test package uses a combination of cmake and cmake_find_package_multi generators with this sequence of cmake commands:

```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_set_vs_runtime()
conan_set_libcxx()
conan_output_dirs_setup()

# Find the QtWidgets library
find_package(qt REQUIRED CONFIG)

# Tell CMake to create the helloworld executable
add_executable(helloworld main.cpp mainwindow.cpp mainwindow.ui resources.qrc)

target_link_libraries(helloworld PRIVATE qt::qt)
```

Notice there is no conan_basic_setup(), but there are three other conan commands. I am on Windows and it links properly, but I cannot get it to execute (well I can when not using conan ;). I think the problem is getting all the appropriate libraries "installed" into the same directory, but unfortunately [import] does not appear to work for the qt recipe. All I get is libEGL and libGLESv2 -- no qt DLLs.

**Comment by jgsogo** [comment] 2021-05-13 14:23
I've been trying this recipe, I can compile and execute (very straightforward), but the result is unexpected: all leters together in labels and buttons. I get the same result in MacOS and Linux 😕 

![image](https://user-images.githubusercontent.com/1406456/118138815-09f8c080-b407-11eb-94f7-23f016c586e2.png)

Probably it is something I'm missing when using this recipe.

**Comment by ericLemanissier** [comment] 2021-05-17 13:50
I can reproduce this on windows too. It seems to be a consequence of the desactivation of harfbuzz. I'll try to see if we can re-enable it

**Comment by yuriy-mochurad** [comment] 2021-05-18 09:06
I am seeing same linking issues for Mac with qt/6.0.4 as @AndreyMlashkin .
```
Undefined symbols for architecture x86_64:
  "_SCDynamicStoreCopyProxies", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_SCNetworkReachabilityCreateWithAddress", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt6Network.a(qnetconmonitor_darwin.mm.o)
  "_SCNetworkReachabilityCreateWithAddressPair", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt6Network.a(qnetconmonitor_darwin.mm.o)
  "_SCNetworkReachabilityGetFlags", referenced from:
      QNetworkConnectionMonitor::setTargets(QHostAddress const&, QHostAddress const&) in libQt6Network.a(qnetconmonitor_darwin.mm.o)
  "_SCNetworkReachabilitySetCallback", referenced from:
      QNetworkConnectionMonitor::~QNetworkConnectionMonitor() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkConnectionMonitor::stopMonitoring() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkConnectionMonitor::startMonitoring() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkStatusMonitor::~QNetworkStatusMonitor() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkStatusMonitor::stop() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
  "_SCNetworkReachabilitySetDispatchQueue", referenced from:
      QNetworkConnectionMonitor::~QNetworkConnectionMonitor() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkConnectionMonitor::stopMonitoring() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkConnectionMonitor::startMonitoring() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkStatusMonitor::~QNetworkStatusMonitor() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
      QNetworkStatusMonitor::stop() in libQt6Network.a(qnetconmonitor_darwin.mm.o)
  "___gss_c_nt_hostbased_service_oid_desc", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_acquire_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_delete_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_display_status", referenced from:
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_import_name", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_init_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_buffer", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_name", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_kSCPropNetProxiesExceptionsList", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesExcludeSimpleHostnames", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesFTPEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesFTPPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesFTPProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPSEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPSPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesHTTPSProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesProxyAutoConfigEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesProxyAutoConfigURLString", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesSOCKSEnable", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesSOCKSPort", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
  "_kSCPropNetProxiesSOCKSProxy", referenced from:
      macQueryInternal(QNetworkProxyQuery const&) in libQt6Network.a(qnetworkproxy_mac.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by ericLemanissier** [comment] 2021-05-18 09:36
@AndreyMlashkin and @yuriy-mochurad, Could you please test with the changes in https://github.com/conan-io/conan-center-index/pull/5547 ?

**Comment by yuriy-mochurad** [comment] 2021-05-18 10:48
I did test that patch and I get slightly different linking issue:
```
Undefined symbols for architecture x86_64:
  "___gss_c_nt_hostbased_service_oid_desc", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_acquire_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_delete_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_display_status", referenced from:
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_import_name", referenced from:
      qGSsapiGetServiceName(QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_init_sec_context", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_buffer", referenced from:
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
      q_GSSAPI_error_int(char const*, unsigned int, int) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_cred", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
  "_gss_release_name", referenced from:
      QAuthenticatorPrivate::parseHttpResponse(QList<std::__1::pair<QByteArray, QByteArray> > const&, bool, QString const&) in libQt6Network.a(qauthenticator.cpp.o)
      qGssapiContinue(QAuthenticatorPrivate*, QByteArray const&) in libQt6Network.a(qauthenticator.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by SSE4** [comment] 2021-05-18 11:02
`gss_` functions seem to be from the [GSS](https://developer.apple.com/documentation/gss/1438466-gss_acquire_cred?language=objc) framework
`SC` functions seem to be from [SystemConfiguration](https://developer.apple.com/documentation/systemconfiguration/kscpropnetproxiesexcludesimplehostnames?language=objc)

probably, it's worth adding the following:
```
self.cpp_info.components["qtCore"].frameworks.append("GSS")
self.cpp_info.components["qtCore"].frameworks.append("SystemConfiguration")
```

around these lines: https://github.com/conan-io/conan-center-index/blob/master/recipes/qt/6.x.x/conanfile.py#L786

**Comment by ericLemanissier** [comment] 2021-05-18 11:09
thanks @yuriy-mochurad !
it should be fixed in the latest version of https://github.com/conan-io/conan-center-index/pull/5547/files. Can you please retry ?

**Comment by AndreyMlashkin** [comment] 2021-05-18 11:32
Will you also update qt/5.15.2 accordingly?

**Comment by yuriy-mochurad** [comment] 2021-05-18 12:54
@ericLemanissier @SSE4 I tested both approaches and both seems to be fixing the issue with linking.

**Comment by SSE4** [comment] 2021-05-18 14:31
okay, then I consider question to be answered

**Comment by jgsogo** [comment] 2021-05-18 15:32
I've tried with a shared build, I [my issue](https://github.com/conan-io/conan-center-index/issues/5450#issuecomment-840595980) is fixed now. Thanks!

I think we can add the `close #5450` to the PR

**Closed** 2021-05-19 08:01 UTC
Labels: question
