### ISSUE TITLE
argparse  argparse/2.1: descrepency between downloaded package files vs actual index file and github version

### ISSUE THREAD

**Issue by kobi-ca** [conan-io/conan-center-index#7253] opened 2021-09-11 19:36 UTC
using https://github.com/p-ranav/argparse
conan-center has v2.1

My remote:
```
conan remote list
conan-center: https://center.conan.io [Verify SSL: True]
```

It was 
```
conan remote list
conan-center: https://conan.bintray.com [Verify SSL: True]
```

and I updated it to point to the new center.conan.io.
```
conan remote update conan-center https://center.conan.io
```

```
conan --version
Conan version 1.40.0
x86_64 machine. Ubuntu 18.04.
Python 3.7.10, using conan in a venv
```
Only using default profile:
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

Per my understanding, this is what I should see:
https://github.com/conan-io/conan-center-index/blob/0be2132ba0d229068bf78770319c51cadfa622c4/recipes/argparse/all/conandata.yml#L3

and indeed when wget this: https://github.com/p-ranav/argparse/archive/v2.1.tar.gz I'm getting the right files (it's a single header C++ library btw)

I tried
```
conan install --build=missing --update ..
```
and even 
```
conan remove argparse
```
and re-installing it. Same header (old, not the v2.1) is downloaded.

my conandata.yml
```
cat ~/.conan/data/argparse/2.1/_/_/export/conandata.yml
sources:
  '2.1':
    sha256: 0a82f464b568b8ee6650fc837f371eb9c81417e2ef9fb3b51f65ad50fa3b8662
    url: https://github.com/p-ranav/argparse/archive/v2.1.tar.gz
```

and here is the diff:
```
wget https://github.com/p-ranav/argparse/archive/v2.1.tar.gz
tar zxvf ./v2.1.tar.gz
md5sum argparse-2.1/include/argparse/argparse.hpp
f60449c9860d46cf3e5926017ccf079e  argparse-2.1/include/argparse/argparse.hpp
 md5sum ~/.conan/data/argparse/2.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/argparse/argparse.hpp
ae35c7d5423ccfd149b7f0fd060c2f87  ~/.conan/data/argparse/2.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/argparse/argparse.hpp

wc -l argparse-2.1/include/argparse/argparse.hpp
1107 argparse-2.1/include/argparse/argparse.hpp

wc -l /usr2/kobic/.conan/data/argparse/2.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/argparse/argparse.hpp
621 ~/.conan/data/argparse/2.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/argparse/argparse.hpp
```

So clearly what conan has in cache and what is in the v2.1 tag are 2 different things.

Question is, why the indexing is saying v2.1, the tgz is OK, but something else resides in the conan center backend.

**Comment by madebr** [comment] 2021-09-12 21:40
I can reproduce.
```
conan remove -f argparse
conan install argparse/2.1@

cd /tmp
rm -rf v2.1.tar.gz argparse-2.1
wget https://github.com/p-ranav/argparse/archive/v2.1.tar.gz
tar xf v2.1.tar.gz

md5sum ~/.conan/data/argparse/2.1/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/argparse/argparse.hpp
md5sum /tmp/argparse-2.1/include/argparse/argparse.hpp
```

The one in the conan cache has `Copyright (c) 2019`.
The one in the 2.1 tarball has `Copyright (c) 2019-2021`

I'm also curious how and what old version of argparse went into conan center.

**Comment by memsharded** [comment] 2021-09-12 21:50
Can verify, the 2.1 contains the (c) 2019, and trying to create the package produces:

```bash
ConanException: sha256 signature failed for 'v2.1.tar.gz' file.
 Provided signature: 0a82f464b568b8ee6650fc837f371eb9c81417e2ef9fb3b51f65ad50fa3b8662
 Computed signature: 44f40a5b9908e722a419973f676bfad4f34d904bf23f89351c477988bc5c4044
```

Changing the signature, produces an incorrect package, (fails at test_package), because of the include location changed: \argparse\argparse, but at least the file is showing the (c)2019-2021

**Comment by memsharded** [comment] 2021-09-12 21:58
I have opened https://github.com/conan-io/conan-center-index/pull/7269, but lets see what they say regarding the tag v2.1 changes.

**Comment by kobi-ca** [comment] 2021-09-14 14:12
question is how conan folks can avoid such accident in the future? is there such a mechanism?

**Comment by Croydon** [comment] 2021-09-14 14:42
> 
> 
> question is how conan folks can avoid such accident in the future? is there such a mechanism?

This is not a Conan issue. Git tags / Releases shouldn't be re-released with changes.

**Closed** 2021-10-16 15:34 UTC
Labels: bug
