### ISSUE TITLE
[package] bzip2/1.0.8: Build failed with ClangCL on Visual Studio

### ISSUE THREAD

**Issue by IRainman** [conan-io/conan-center-index#8175] opened 2021-11-24 16:38 UTC
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **bzip2/1.0.8**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 16**
  * Docker image: **conanio/gcc8**
  * Conan version: **conan 1.42.2**
  * Python version: **Python 3.9.7**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.version=16
compiler.runtime='MT'
compiler.toolset=ClangCL
compiler.cppstd=20
[options]
[build_requires]
[env]
```

### Logs (Include/Attach if Applicable)
<details><summary>Click to expand log</summary>

```
bzip2/1.0.8: Copying sources to build folder
bzip2/1.0.8: Building your package in C:\Users\L\.conan\data\bzip2\1.0.8\_\_\build\d339bef92f6bde57afebf0444dd14c3cde957b3f
bzip2/1.0.8: Generator cmake created conanbuildinfo.cmake
bzip2/1.0.8: Aggregating env generators
bzip2/1.0.8: Calling build()
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "C:/Users/L/.conan/data/bzip2/1.0.8/_/_/build/d339bef92f6bde57afebf0444dd14c3cde957b3f/CMakeFiles/CMakeOutput.log".
See also "C:/Users/L/.conan/data/bzip2/1.0.8/_/_/build/d339bef92f6bde57afebf0444dd14c3cde957b3f/CMakeFiles/CMakeError.log".
bzip2/1.0.8:
bzip2/1.0.8: ERROR: Package 'd339bef92f6bde57afebf0444dd14c3cde957b3f' build failed
bzip2/1.0.8: WARN: Build folder C:\Users\L\.conan\data\bzip2\1.0.8\_\_\build\d339bef92f6bde57afebf0444dd14c3cde957b3f
ERROR: bzip2/1.0.8: Error in build() method, line 63
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 57
        self._cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\L\.conan\data\bzip2\1.0.8\_\_\build\d339bef92f6bde57afebf0444dd14c3cde957b3f && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MT" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP20" -DCONAN_C_FLAGS="/MP20" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\L\.conan\data\bzip2\1.0.8\_\_\package\d339bef92f6bde57afebf0444dd14c3cde957b3f" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DBZ2_VERSION_STRING="1.0.8" -DBZ2_VERSION_MAJOR="1" -DBZ2_BUILD_EXE="True" -Wno-dev -T "ClangCL" C:\Users\L\.conan\data\bzip2\1.0.8\_\_\build\d339bef92f6bde57afebf0444dd14c3cde957b3f
```

</details>

**Comment by ericLemanissier** [comment] 2021-11-29 09:30
cannot reproduce on https://github.com/eirikb/proof-of-conan/runs/4351559242?check_suite_focus=true#step:8:83
Did you run in proper visual studio environment ? (pcre succeeds too)

**Comment by perseoGI** [comment] 2024-09-10 12:43
Same as in https://github.com/conan-io/conan-center-index/issues/8173,
I'm closing this issue as this should have been resolved a long time ago.
Thank you for your report!

Happy coding 🐸

**Closed by perseoGI** 2024-09-10 12:43 UTC
Labels: bug
