### ISSUE TITLE
[request] onnxruntime/1.13.1

### ISSUE THREAD

**Issue by elejke** [conan-io/conan-center-index#16699] opened 2023-03-25 09:05 UTC
### Package Name/Version

onnxruntime/1.13.1

### Webpage

https://www.onnxruntime.ai/

### Source code

https://github.com/microsoft/onnxruntime

### Description of the library/tool

ONNX Runtime is a cross-platform inference and training machine-learning accelerator compatible with deep learning frameworks, PyTorch and TensorFlow/Keras, as well as classical machine learning libraries such as scikit-learn, and more.

There [was](https://github.com/conan-io/conan-center-index/pull/5180) one good try to create a recipe from @CAMOBAP, even I managed to build it now for Mac OS for version 1.7.1 and test_package passes correctly.

On Windows it have some errors, but it looks like there [was a solution](https://github.com/conan-io/conan-center-index/pull/5180#issuecomment-916999504) for them before from @fdgStilla (windows wil library should be added as build_requirement) 

As for now 1.7.1 is too old and it will be perfect to update the recipe and finally get it to the conan center.

This is the most popular library for neural network inference on all platforms!

**Comment by SpaceIm** [comment] 2023-03-26 19:18
duplicate of https://github.com/conan-io/conan-center-index/issues/4806

**Comment by elejke** [comment] 2023-03-26 21:41
> duplicate of #4806

I have managed to reproduce results from @CAMOBAP on Mac / Linux / Windows (with some bug fixes)

But the main problem with this package is that they using subprojects to random commits (looks like). And that is why I think it will be many problems to build such new version, but, you can close it if needed, I will up https://github.com/conan-io/conan-center-index/issues/4806

**Comment by gmeeker** [comment] 2023-04-01 03:41
Okay, I've put up #16842 but it could use a lot of help.  I've tested macOS, Windows, and Linux, but not iOS or Android, and of course all the options for execution providers that should go in there.

**Closed** 2023-05-01 08:45 UTC
Labels: library request
