### ISSUE TITLE
[conan.io/center] How to add a new package link is broken

### ISSUE THREAD

**Issue by adithyan** [conan-io/conan-center-index#15793] opened 2023-02-07 01:42 UTC
### What is your problem/feature request?

Please find the attachment below, The link is broken
![image](https://user-images.githubusercontent.com/1707567/217126490-aa1e74bb-0b6f-4b93-8566-52b6fc194639.png)

**Comment by ErikTempelaarVO** [comment] 2023-02-10 13:05
The link points to this URL:
https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md

Seems that it's now here:
https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/README.md

May have been caused by this:
#15004

**Comment by prince-chrismc** [comment] 2023-07-31 21:03
This was fixed in another issue of a private repo but not linked. 

There's a new website so this is not there either :)

**Closed by prince-chrismc** 2023-07-31 21:03 UTC
Labels: conan.io/center
