### ISSUE TITLE
[package] qwt/6.2.0: Compilation error with gcc9 profile

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-center-index#12830] opened 2022-09-05 10:10 UTC
### Package and Environment Details

* Package Name/Version: **qwt/6.2.0**
* Operating System+version: **Debian bullseye/sid from Github codespace**
* Compiler+version: **GCC 9**
* Conan version: **conan 1.52.0**
* Python version: **Python 3.10.4**

### Conan profile

[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]

### Steps to reproduce

As CONAN_SYSREQUIRES_MODE=enabled use doesn't succeed to install all requirement we do it manually:

`
sudo apt install -y libx11-xcb-dev  libfontenc-dev  libxaw7-dev  libxcomposite-dev  libxcursor-dev  libxdamage-dev  libxfixes-dev  libxi-dev  libxinerama-dev  libxkbfile-dev  libxmu-dev  libxmuu-dev  libxpm-dev  libxrandr-dev  libxres-dev  libxtst-dev  libxv-dev  libxvmc-dev  libxxf86vm-dev  libxcb-render0-dev  libxcb-render-util0-dev  libxcb-xkb-dev  libxcb-icccm4-dev  libxcb-image0-dev  libxcb-keysyms1-dev  libxcb-randr0-dev  libxcb-shape0-dev  libxcb-sync-dev  libxcb-xfixes0-dev  libxcb-xinerama0-dev  libxcb-dri3-dev libxcb-util-dev
`
`sudo apt install -y libxcb-util-dev`

To have qmake as we don't have it through conan center as we can have it with cmake as tool_requires:

`sudo apt install -y qt5-qmake`

Strangly qwt build doesn't looks for qt in conan cache, then we install qt dev files from apt repo:

`sudo apt install -y qtbase5-dev`

Then we try to build qwt:

`conan create . --build missing --profile:build profile --profile:host profile`

But we get compilation error:

`error: cannot convert ‘const QMetaObject* const*’ to ‘const QMetaObject::SuperData*’ in initialization`

See https://github.com/EstebanDugueperoux2/qwtExample to reproduce.

Regards.

### Logs

<details><summary>Click to expand log</summary>

```
compiling ../source_subfolder/src/qwt_polar_canvas.cpp
In file included from ../source_subfolder/src/qwt_plot_glcanvas.cpp:239:
moc/moc_qwt_plot_glcanvas.cpp:153:5: error: cannot convert ‘const QMetaObject* const*’ to ‘const QMetaObject::SuperData*’ in initialization
  153 |     qt_meta_extradata_QwtPlotGLCanvas,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     |
      |     const QMetaObject* const*
make[1]: *** [Makefile:2169: obj/qwt_plot_glcanvas.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../source_subfolder/src/qwt_plot_opengl_canvas.cpp:257:
moc/moc_qwt_plot_opengl_canvas.cpp:154:5: error: cannot convert ‘const QMetaObject* const*’ to ‘const QMetaObject::SuperData*’ in initialization
  154 |     qt_meta_extradata_QwtPlotOpenGLCanvas,
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     |
      |     const QMetaObject* const*
make[1]: *** [Makefile:2181: obj/qwt_plot_opengl_canvas.o] Error 1
make[1]: Leaving directory '/home/codespace/.conan/data/qwt/6.2.0/_/_/build/54a7422544bfa3320a8a50eacf7c38ca26e754a9/src'
make: *** [Makefile:53: sub-src-make_first-ordered] Error 2
qwt/6.2.0: 
qwt/6.2.0: ERROR: Package '54a7422544bfa3320a8a50eacf7c38ca26e754a9' build failed
qwt/6.2.0: WARN: Build folder /home/codespace/.conan/data/qwt/6.2.0/_/_/build/54a7422544bfa3320a8a50eacf7c38ca26e754a9
ERROR: qwt/6.2.0: Error in build() method, line 99
        self.run("make -j {}".format(tools.cpu_count()))
        ConanException: Error 2 while executing make -j 4
```

</details>

**Comment by ericLemanissier** [comment] 2022-09-05 10:37
the first problem should be solved by adding `  -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True` on your command line cf https://docs.conan.io/en/latest/reference/conanfile/tools/system/package_manager.html#conan-tools-system-package-manager-config. You can also put these in your profile, or in global.conf

The fact that qwt recipes does not find qmake should be solved with https://github.com/conan-io/conan-center-index/pull/12831, so please do not install system qt or qmake.

**Comment by EstebanDugueperoux2** [comment] 2022-09-05 12:56
Hi Eric,

Thanks for your efficient support.
A better way could be to have qwt use cmake instead of qmake no?
As proposed in https://sourceforge.net/p/qwt/patches/79/.

Regards.

**Comment by ericLemanissier** [comment] 2022-09-05 13:10
you would still miss moc, so it would not be a solution

**Comment by EstebanDugueperoux2** [comment] 2022-09-05 13:56
In my specific case, I'm not in a cross-compilation scenario.
I'm only interested by x86_64 binaries.
Is it possible to have a restreined fix?

**Comment by ericLemanissier** [comment] 2022-09-05 14:02
you can add qt/5.15.2 to the `tool_requires` section in your profile

**Comment by EstebanDugueperoux2** [comment] 2022-09-05 14:56
I have added another commit in https://github.com/EstebanDugueperoux2/qwtExample to test that but get following errors:

```
...
linking ../bin/curvedemo
g++: error: /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib/libfontconfig.so: No such file or directory
g++: error: /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib/libfreetype.so: No such file or directory
g++: error: /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib/libz.so: No such file or directory
g++: error: /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib/libQt5LinuxAccessibilitySupport.a: No such file or directory
g++: error: /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib/libQt5VulkanSupport.a: No such file or directory
...
```

And this is the content of qt5 conan package in my cache:

```
@EstebanDugueperoux2 ➜ /workspaces/qwtExample (main ✗) $ ls /home/codespace/.conan/data/qt/5.15.2/_/_/package/e582f9d156d6ef3cd4f0a641280d3bdd1a9096ae/lib
cmake                             libQt5EdidSupport.a               libQt5GlxSupport.prl    libQt5OpenGL.a                       libQt5ServiceSupport.prl  libQt5XcbQpa.a
libQt5AccessibilitySupport.a      libQt5EdidSupport.prl             libQt5Gui.a             libQt5OpenGLExtensions.a             libQt5Sql.a               libQt5XcbQpa.prl
libQt5AccessibilitySupport.prl    libQt5EventDispatcherSupport.a    libQt5Gui.prl           libQt5OpenGLExtensions.prl           libQt5Sql.prl             libQt5XkbCommonSupport.a
libQt5Concurrent.a                libQt5EventDispatcherSupport.prl  libQt5InputSupport.a    libQt5OpenGL.prl                     libQt5Test.a              libQt5XkbCommonSupport.prl
libQt5Concurrent.prl              libQt5FbSupport.a                 libQt5InputSupport.prl  libQt5PlatformCompositorSupport.a    libQt5Test.prl            libQt5Xml.a
libQt5Core.a                      libQt5FbSupport.prl               libQt5KmsSupport.a      libQt5PlatformCompositorSupport.prl  libQt5ThemeSupport.a      libQt5Xml.prl
libQt5Core.prl                    libQt5FontDatabaseSupport.a       libQt5KmsSupport.prl    libQt5PrintSupport.a                 libQt5ThemeSupport.prl    metatypes
libQt5DeviceDiscoverySupport.a    libQt5FontDatabaseSupport.prl     libQt5Network.a         libQt5PrintSupport.prl               libQt5Widgets.a
libQt5DeviceDiscoverySupport.prl  libQt5GlxSupport.a                libQt5Network.prl       libQt5ServiceSupport.a               libQt5Widgets.prl
```

It is stranged because shared option is at False by default.

Regards.

**Comment by ericLemanissier** [comment] 2022-09-05 14:59
this should be addressed by this part of the PR: https://github.com/conan-io/conan-center-index/pull/12831/files#diff-881dd1a2a6606bba307e34450ae2cc3c0a44aae04078cc771234c5b8db62faacR86

**Comment by Jihadist** [comment] 2022-09-06 07:00
> Hi Eric,
> 
> Thanks for your efficient support. A better way could be to have qwt use cmake instead of qmake no? As proposed in https://sourceforge.net/p/qwt/patches/79/.


It's not a conan issue, by the way there are at least 4 different cmake proposals for qwt 
https://github.com/xantares/qwt-cmake from your issue
and 3 more from another (https://sourceforge.net/p/qwt/feature-requests/95/) issue
https://github.com/ericriff/qwt
https://github.com/biddisco/qwt
https://github.com/MehdiChinoune/qwt

**Comment by EstebanDugueperoux2** [comment] 2022-09-06 08:33
In my case, I prefer cmake because my CI builds are using Conan Docker official images which don't contains qmake of course and cmake is available through tool requirement, in case a binary not available for my profile.
In community point of view cmake use more used but qwt is a single developer project which prefer qmake unfortunatly.

@ericLemanissier do you understand PR logs errors?

**Comment by Jihadist** [comment] 2022-09-06 08:39
I also prefer cmake but if we wanna use cmake upstream have to contain cmake scripts

**Comment by ericLemanissier** [comment] 2022-09-06 08:54
@EstebanDugueperoux2 I do understand the PR error, and it is bad :(
The problem is that qmake has some paths to dependencies hardcoded as absolute paths, and in the context of conan-center CI, the absolute paths to package folder changes from one PR to the other.
The "proper" fix would be to modify qt recipe so that qmake does not hardcode these absolute paths, but it most probably involves patching, and testing with different folders (which CCI cannot do in a single PR).
The shortest path to success is probably to build qwt using cmake instead. @ericriff is already a community reviewer on CCI, would you be ok if we used https://github.com/ericriff/qwt/blob/master/CMakeLists.txt ?

**Comment by Jihadist** [comment] 2022-09-06 09:10
@ericLemanissier i look through cmakelists by @ericriff  and @MehdiChinoune, the last looks better because it supports qt5,6, shared libs, dont use globs and qwt modules as an original qmake. But of course proposal by ericriff is simplier

**Comment by ericLemanissier** [comment] 2022-09-06 11:35
you need to enable option `qt:qtsvg=True`

**Closed** 2022-09-20 07:33 UTC
Labels: bug

**Comment by ericLemanissier** [comment] 2022-09-20 07:49
You are welcome.
Nothing is ever removed from conan-center (remote). When a recipe is deleted in conan-center-index (git), the corresponding package in conan-center just stops being updated (no rew recipe revision or binaries)

**Comment by uilianries** [comment] 2022-09-20 10:44
Plus, there is a topis on FAQs about it: https://github.com/conan-io/conan-center-index/blob/master/docs/faqs.md#what-is-the-policy-for-removing-older-versions-of-a-package
