### ISSUE TITLE
[package] aws-sdk-cpp/1.8.130: name conflicts with other AWS packages 

### ISSUE THREAD

**Issue by dvirtz** [conan-io/conan-center-index#7099] opened 2021-08-28 22:16 UTC
4 AWS packages: `aws-c-common`, `aws-c-event-stream`, `aws-checksums`  and `aws-sdk-cpp` use `AWS` as the name for the `cmake_find_package` and `cmake_find_package_multi` generators. This causes conflicts between CMake variable names in the find modules generated by conan.
E.g. for `cmake_find_package_multi`, running cmake with `--trace-expand` shows that the line
```
set_property(TARGET AWS::AWS APPEND PROPERTY INTERFACE_LINK_LIBRARIES
                 $<$<CONFIG:Debug>:${AWS_COMPONENTS_DEBUG}>
                 $<$<CONFIG:Release>:${AWS_COMPONENTS_RELEASE}>
                 $<$<CONFIG:RelWithDebInfo>:${AWS_COMPONENTS_RELWITHDEBINFO}>
                 $<$<CONFIG:MinSizeRel>:${AWS_COMPONENTS_MINSIZEREL}>)
```
from `AWSSDKConfig.cmake` expands to
```
/projects/uplynk/dependencies/slicer_Linux_64/AWSSDKConfig.cmake(949):  set_property(TARGET AWS::AWS APPEND PROPERTY INTERFACE_LINK_LIBRARIES $<$<CONFIG:Debug>:> $<$<CONFIG:Release>:> $<$<CONFIG:RelWithDebInfo>:AWS::aws-checksums> $<$<CONFIG:MinSizeRel>:> )
```
which shows that the value for `AWS_COMPONENTS_RELWITHDEBINFO` is read from the config file of `aws-checksums` which sets a variable by the same name.
Eventually, this causes cmake not to link the required libraries from `aws-sdk-cpp`.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **aws-sdk-cpp/1.8.130**
  * Conan version: **conan 1.36.0**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)
```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[conf]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)
build the project from https://github.com/dvirtz/bugs/tree/conan-aws-sdk-cpp

**Comment by madebr** [comment] 2021-08-29 17:51
This is a conan bug.
I propose creating a small reproducer and report it to conan.

Perhaps @danimtb can help you.
If memory servers, he added components to conan.

**Comment by dvirtz** [comment] 2021-08-29 18:01
wouldn't the bug be prevented if each library had a different name?
what's the reason behind setting name to "AWS" on all those packages?

**Comment by madebr** [comment] 2021-08-29 18:03
All aws packages create targets in the `AWS::` namespace.
An alternative would be to create targets in a private namespace,
and add a `conan-targets.cmake` module that creates the `AWS::` targets.

**Comment by SpaceIm** [comment] 2021-08-29 20:10
> An alternative would be to create targets in a private namespace,
> and add a conan-targets.cmake module that creates the AWS:: targets.

Too much boilerplate, it mush be fixed in conan.

More or less related to https://github.com/conan-io/conan/issues/8196

By the way, is `AWS::AWS` an official target?

**Comment by madebr** [comment] 2021-08-29 21:11
> > An alternative would be to create targets in a private namespace,
> > and add a conan-targets.cmake module that creates the AWS:: targets.
> 
> Too much boilerplate, it must be fixed in conan.

Couldn't agree more. 

> More or less related to [conan-io/conan#8196](https://github.com/conan-io/conan/issues/8196). Eventually, those generators (cmake_find_package[_multi], CMakeDeps) should allow to disable the `namespace::namespace` target in the recipe (and internally, conan should link to a `recipeName::recipeName` or something very specific like `conan::recipeName` target when others Find/config file depend on the global target of a recipe).

:+1: 

> By the way, is `AWS::AWS` an official target?

Afaik, no.
The target is conan specific. It looks like conan corrupts its own targets.
I want to see an example that causes an error though.

**Comment by dvirtz** [comment] 2021-08-30 08:42
this looks exactly like https://github.com/conan-io/conan/issues/8196 to me. to reproduce:
```sh
git clone https://github.com/dvirtz/bugs.git
cd bugs
git checkout conan-aws-sdk-cpp
./build.sh
```

**Closed** 2024-12-18 14:57 UTC
Labels: bug
