### ISSUE TITLE
[service] Add gcc 10 Support

### ISSUE THREAD

**Issue by sachnk** [conan-io/conan-center-index#1760] opened 2020-05-27 22:39 UTC
[gcc 10.1](https://gcc.gnu.org/gcc-10/) was released on 05/07/2020.

Adding gcc10 to the list of supported linux compilers so that packages available in ConanCenter are prebuilt with gcc10 would be helpful for people trying out the latest c++20 features.

This is the same request as when [gcc9 was added](https://github.com/conan-io/conan-center-index/issues/18).

**Comment by Croydon** [comment] 2020-05-27 23:39
Duplicate of #1587

**Closed** 2020-05-28 08:54 UTC
