### ISSUE TITLE
[package] Protobuf: CMake variables capitalization 

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan-center-index#5368] opened 2021-04-29 18:59 UTC
According to CMake documentation, protobuf's targets should be all lowercase `protobuf::libprotobuf` (which Conan mimics correctly) but the variables should start with a capital P, like `Protobuf_INCLUDE_DIRS`. The current recipe provide variables that start with a lower case `p`, E.g. `protobuf_INCLUDE_DIRS`. 
https://cmake.org/cmake/help/latest/module/FindProtobuf.html 

If I change `self.cpp_info.names["cmake_find_package"] = "protobuf"` to `self.cpp_info.names["cmake_find_package"] = "Protobuf"` then I get the right variables but the target names also chage.

Can this be fixed?

**Comment by SpaceIm** [comment] 2021-04-29 19:05
It can be fixed, with the same tricks used in bzip2 recipe for example.

**Comment by Croydon** [comment] 2021-04-30 07:46
Duplicate of #3492

**Comment by perseoGI** [comment] 2024-09-05 15:31
Hi there!
I was reviewing old issues like this one.
This problem was addressed in this PR https://github.com/conan-io/conan-center-index/pull/8820
So I'm closing this issue!

Happy coding 🐸

**Closed by perseoGI** 2024-09-05 15:31 UTC
Labels: bug
