### ISSUE TITLE
[question] Source Code Mirror of manually built dependency down

### ISSUE THREAD

**Issue by simue** [conan-io/conan-center-index#7967] opened 2021-11-05 14:42 UTC
I am building dependencies for the md5 examples myself, since they are not in conancenter in the needed configuration.
When conan tries to get the sources for `pcre`, it fails with a handshake time out.
Upon inspection it is obvious, that the ftp server from pcre project is down.
https://downforeveryoneorjustme.com/ftp.pcre.org

What should I do in such a case? Do I have to wait for pcre to patch their recipes, or can I redirect the source mirror url myself?

## Log
```
pcre/8.45: Configuring sources in /home/simue/.conan/data/pcre/8.45/_/_/source

ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.45.tar.gz (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1114: The handshake operation timed out')))'
Waiting 5 seconds to retry...
```

**Comment by memsharded** [comment] 2021-11-05 15:38
This is a blocking "bug"= not working, but the cause is external to Conan. Maybe the recipe could provide a mirror if there is one. Maybe ``pcre`` server is restored quickly

**Comment by SpaceIm** [comment] 2021-11-05 16:24
fixed in https://github.com/conan-io/conan-center-index/pull/7956

**Comment by simue** [comment] 2021-11-06 08:57
Thank you both, I will be able to test this on Monday.

**Comment by simue** [comment] 2021-11-08 10:12
I see that in adc2bc6a637012a7cfa826db1e8c014d7ceb5627 the sha hashes were changed. How would I create them for updated mirros? is this automatically done by conan?
Further more I tested memsharded's workaround and it fails when pcre's test_package is built. It can't find the header - do I need to provide the location of the header file and how would I do this?

Since the lib itself was built successfully I got a working pcre package anyways.
Clearing pcre from cache and installing again works, too.

## Log
```
-- Found: /home/simue/.conan/data/zlib/1.2.11/_/_/package/1b8d0b0212b9e0dbf9302201735e4c96e1c280c1/lib/libz.a
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR


-- Build files have been written to: /home/simue/repos/conan-center-index/recipes/pcre/all/test_package/build/6b7349d69949be481b899ae109aba9c197e810ed
Scanning dependencies of target test_package
[ 50%] Building C object CMakeFiles/test_package.dir/test_package.c.o
/home/simue/repos/conan-center-index/recipes/pcre/all/test_package/test_package.c:41:10: fatal error: pcre.h: No such file or directory
   41 | #include "pcre.h"
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/test_package.dir/build.make:63: CMakeFiles/test_package.dir/test_package.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/test_package.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
ERROR: pcre/8.45 (test package): Error in build() method, line 12
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/home/simue/repos/conan-center-index/recipes/pcre/all/test_package/build/6b7349d69949be481b899ae109aba9c197e810ed' '--' '-j8'

```

**Comment by perseoGI** [comment] 2024-09-10 10:31
Hi there, 
I was reviewing old issues and I have come across this one.

> How would I create them for updated mirros? is this automatically done by conan?

The recommended way to calculate the `sha256` is described in here https://github.com/conan-io/conan-center-index/blob/master/docs/adding_packages/conandata_yml_format.md#sha256

Anyways, I'm closing this issue as `pcre` recipe has suffer plenty of modifications since this issue was open. Between them, we do not have anymore multiple remotes for each version.  

Happy coding 🐸

**Closed by perseoGI** 2024-09-10 10:31 UTC
Labels: bug, enhancement
