### ISSUE TITLE
[question] cmake/3.20.0 is not available for conan v2 in ubunut 20.04 gcc version 9

### ISSUE THREAD

**Issue by sabapathi20** [conan-io/conan-center-index#24937] opened 2024-08-14 12:57 UTC
### What is your question?

Hi Team,

I'm looking for package cmak/3.20.0 but it wasn't available for conan v2 in ( Ubunut 20.04 , gcc version 9, arch x86_64 )

**Comment by jcar87** [comment] 2024-08-14 14:30
Closed as duplicate of https://github.com/conan-io/conan-center-index/issues/24939

**Closed by jcar87** 2024-08-14 14:30 UTC
Labels: question
